<a href="https://colab.research.google.com/github/HrishikeshTalukdar/Rishx-dev/blob/master/EDA_IPL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Necessary Liabrary

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df1 = pd.read_csv("/content/drive/MyDrive/Data science/EDA May 2026/IPL Ball-by-Ball 2008-2020 (2).csv")
df2 = pd.read_csv("/content/drive/MyDrive/Data science/EDA May 2026/IPL Matches 2008-2020 (1).csv")

In [4]:
df1.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore

In [5]:
df2.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [6]:
len(df1)

193468

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193468 entries, 0 to 193467
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                193468 non-null  int64
 1   inning            193468 non-null  int64
 2   over              193468 non-null  int64
 3   ball              193468 non-null  int64
 4   batsman           193468 non-null  object
 5   non_striker       193468 non-null  object
 6   bowler            193468 non-null  object
 7   batsman_runs      193468 non-null  int64
 8   extra_runs        193468 non-null  int64
 9   total_runs        193468 non-null  int64
 10  non_boundary      193468 non-null  int64
 11  is_wicket         193468 non-null  int64
 12  dismissal_kind    9495 non-null    object
 13  player_dismissed  9495 non-null    object
 14  fielder           6784 non-null    object
 15  extras_type       10233 non-null   object
 16  batting_team      193468 non-null  object
 17  bowling_team      193277 non-null  object
dtypes: int64(9), object(9)
memory usage: 26.6+ MB

In [8]:
len(df2)

816

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [10]:
df1.isnull().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind      183973
player_dismissed    183973
fielder             186684
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [11]:
df2.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [12]:
df1['dismissal_kind']= df1['dismissal_kind'].fillna('no_dismissal')

In [13]:
df1['dismissal_kind']

0         no_dismissal
1         no_dismissal
2         no_dismissal
3         no_dismissal
4         no_dismissal
              ...
193463    no_dismissal
193464    no_dismissal
193465    no_dismissal
193466    no_dismissal
193467    no_dismissal
Name: dismissal_kind, Length: 193468, dtype: object

In [14]:
df1.isnull().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind           0
player_dismissed    183973
fielder             186684
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [15]:
df1['player_dismissed'].unique()

array([nan, 'RT Ponting', 'DJ Hussey', 'SC Ganguly', 'MV Boucher',
       'B Akhil', 'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi',
       'JH Kallis', 'W Jaffer', 'R Dravid', 'V Kohli', 'SK Raina',
       'JDP Oram', 'PA Patel', 'ML Hayden', 'MS Dhoni', 'JR Hopes',
       'Yuvraj Singh', 'KC Sangakkara', 'K Goel', 'SK Warne', 'V Sehwag',
       'T Kohli', 'YK Pathan', 'SR Watson', 'DS Lehmann', 'M Kaif',
       'M Rawat', 'RA Jadeja', 'DJ Thornely', 'L Ronchi', 'ST Jayasuriya',
       'PR Shah', 'RV Uthappa', 'AM Nayar', 'SM Pollock', 'S Chanderpaul',
       'LRPL Taylor', 'BB McCullum', 'WP Saha', 'AS Yadav', 'A Symonds',
       'WPUJC Vaas', 'SB Bangar', 'PP Ojha', 'Y Venugopal Rao',
       'VVS Laxman', 'AC Gilchrist', 'RG Sharma', 'SB Styris',
       'Mohammad Hafeez', 'Kamran Akmal', 'DPMD Jayawardene', 'IK Pathan',
       'B Lee', 'S Sohal', 'G Gambhir', 'Shahid Afridi', 'MEK Hussey',
       'Harbhajan Singh', 'DJ Bravo', 'MA Khote', 'GC Smith',
       'D Salunkhe', 'PP Chawla', 'S Sreesanth', 'VRV Singh', 'RR Sarwan',
       'SS Tiwary', 'P Kumar', 'M Kartik', 'LR Shukla', 'AB Agarkar',
       'AM Rahane', 'SM Katich', 'TM Srivastava', 'S Dhawan',
       'Shoaib Malik', 'KD Karthik', 'R Bhatia', 'MK Tiwary',
       'MF Maharoof', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'SA Asnodkar',
       'BJ Hodge', 'Salman Butt', 'Umar Gul', 'AB Dinda', 'SP Fleming',
       'S Vidyut', 'JA Morkel', 'LPC Silva', 'Misbah-ul-Haq',
       'DB Ravi Teja', 'RP Singh', 'SE Marsh', 'AB de Villiers',
       'YV Takawale', 'Mohammad Asif', 'GD McGrath', 'PJ Sangwan',
       'S Badrinath', 'Joginder Sharma', 'M Muralitharan', 'M Ntini',
       'DT Patil', 'A Kumble', 'S Anirudha', 'Sohail Tanvir',
       'SK Trivedi', 'CK Kapugedera', 'A Chopra', 'J Arunkumar',
       'T Taibu', 'R Vinay Kumar', 'SP Goswami', 'AD Mascarenhas',
       'A Mishra', 'VY Mahesh', 'TM Dilshan', 'SR Tendulkar',
       'Younis Khan', 'Niraj Patel', 'Shoaib Akhtar', 'I Sharma', 'H Das',
       'DR Smith', 'SD Chitnis', 'A Nehra', 'VS Yeligati', 'MS Gony',
       'L Balaji', 'LA Pomersbach', 'A Nel', 'A Mukund', 'WA Mota',
       'JP Duminy', 'A Flintoff', 'KP Pietersen', 'JD Ryder',
       'T Henderson', 'MM Patel', 'Kamran Khan', 'RS Bopara',
       'MC Henriques', 'CH Gayle', 'R Bishnoi', 'KV Sharma',
       'PC Valthaty', 'RJ Quiney', 'Yashpal Singh', 'Pankaj Singh',
       'FH Edwards', 'AS Raut', 'AN Ghosh', 'BAW Mendis', 'DL Vettori',
       'RE van der Merwe', 'RR Powar', 'AA Bilakhia', 'TL Suman',
       'Shoaib Ahmed', 'GR Napier', 'MN van Wyk', 'LA Carseldine',
       'NV Ojha', 'M Vijay', 'DA Warner', 'SB Jakati', 'M Manhas',
       'RJ Harris', 'D du Preez', 'RR Raje', 'DS Kulkarni', 'M Morkel',
       'AD Mathews', 'S Tyagi', 'SL Malinga', 'C Nanda', 'J Botha',
       'A Singh', 'GJ Bailey', 'AB McDonald', 'Y Nagar', 'SS Shaikh',
       'R Ashwin', 'T Thushara', 'Mohammad Ashraful', 'Anirudh Singh',
       'CA Pujara', 'AP Tare', 'AT Rayudu', 'R Sathish',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'EJG Morgan',
       'JM Kemp', 'OA Shah', 'RS Gavaskar', 'SE Bond', 'KA Pollard',
       'DP Nannes', 'DR Martyn', 'S Narwal', 'MJ Lumb', 'AB Barath',
       'FY Fazal', 'MD Mishra', 'S Ladda', 'J Theron', 'SJ Srivastava',
       'R Sharma', 'Mandeep Singh', 'AC Voges', 'Jaskaran Singh',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'KM Jadhav', 'SW Tait', 'A Mithun', 'AP Dole', 'Harmeet Singh',
       'R McLaren', 'S Sriram', 'KP Appanna', 'C Madan', 'AG Paunikar',
       'MR Marsh', 'AJ Finch', 'STR Binny', 'B Sumanth', 'IR Jaggi',
       'DT Christian', 'MA Agarwal', 'RV Gomez', 'UT Yadav', 'UBT Chand',
       'DJ Jacobs', 'Sunny Singh', 'AL Menaria', 'AUK Pathan',
       'WD Parnell', 'JJ van der Wath', 'R Ninan', 'MS Wade',
       'JEC Franklin', 'TD Paine', 'SB Wagh', 'Shakib Al Hasan',
       'S Randiv', 'BJ Haddin', 'NLTC Perera', 'JE Taylor', 'NL McCullum',
       'RN ten Doeschate', 'TR Birt', 'M Klinger', 'Harpreet Singh',
       'Bipul Sharma', 'AC Blizzard', 'CA Ingram', 'S Nadeem',
       'DH Yagnik', 'KB Arun Karthik', 'AA Chavan', 'ND Doshi',
       'CJ Ferguson', 'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt',
       'F du Plessis', 'RE Levi', 'DE Bollinger', 'SA Yadav',
       'MN Samuels', 'B Kumar', 'SPD Smith', 'GJ Maxwell', 'HV Patel',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'JP Faulkner',
       'KK Cooper', 'GB Hogg', 'RR Bhatkal', 'CJ McKay', 'N Saini',
       'DA Miller', 'P Negi', 'Azhar Mahmood', 'AC Thomas', 'RJ Peterson',
       'A Ashish Reddy', 'V Pratap Singh', 'MJ Clarke', 'Gurkeerat Singh',
       'VR Aaron', 'AP Majumdar', 'PA Reddy', 'AD Russell', 'CA Lynn',
       'Sunny Gupta', 'MC Juneja', 'KK Nair', 'GH Vihari', 'MDKJ Perera',
       'B Laughlin', 'Mohammed Shami', 'BMAJ Mendis', 'M Vohra',
       'R Rampaul', 'P Awana', 'SMSM Senanayake', 'BJ Rohrer', 'KL Rahul',
       'J Syed Mohammad', 'BB Samantray', 'Q de Kock', 'R Dhawan',
       'MG Johnson', 'LJ Wright', 'AG Murtaza', 'IC Pandey',
       'X Thalaivan Sargunam', 'DJG Sammy', 'SV Samson', 'KW Richardson',
       'CH Morris', 'MM Sharma', 'CM Gautam', 'UA Birla', 'Parvez Rasool',
       'Sachin Baby', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JDS Neesham', 'PV Tambe', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'LMP Simmons', 'VH Zol',
       'Imran Tahir', 'R Shukla', 'BCJ Cutting', 'BE Hendricks',
       'M de Lange', 'S Gopal', 'R Tewatia', 'JO Holder', 'JD Unadkat',
       'SS Iyer', 'DJ Hooda', 'SA Abbott', 'AN Ahmed', 'KS Williamson',
       'Iqbal Abdulla', 'SN Khan', 'D Wiese', 'HH Pandya',
       'MJ McClenaghan', 'Anureet Singh', 'DJ Muthuswami', 'PJ Cummins',
       'Karanveer Singh', 'Sandeep Sharma', 'J Suchith', 'JC Buttler',
       'CR Brathwaite', 'MP Stoinis', 'Ishan Kishan', 'C Munro',
       'AD Nath', 'MJ Guptill', 'P Sahu', 'TM Head', 'M Ashwin',
       'KH Pandya', 'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'JJ Bumrah', 'A Zampa', 'N Rana', 'S Kaushik',
       'F Behardien', 'KJ Abbott', 'ER Dwivedi', 'CJ Jordan', 'S Aravind',
       'YS Chahal', 'TS Mills', 'BA Stokes', 'JJ Roy', 'Vishnu Vinod',
       'CR Woakes', 'RA Tripathi', 'DL Chahar', 'V Shankar',
       'Rashid Khan', 'SN Thakur', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'K Rabada', 'AJ Tye', 'Kuldeep Yadav',
       'SP Jackson', 'Ankit Soni', 'A Choudhary', 'AS Rajpoot',
       'Washington Sundar', 'E Lewis', 'MA Wood', 'RK Singh', 'DJM Short',
       'K Gowtham', 'S Kaul', 'Mujeeb Ur Rahman', 'Shivam Mavi',
       'Shubman Gill', 'TK Curran', 'TA Boult', 'H Klaasen', 'RK Bhui',
       'JC Archer', 'PP Shaw', 'LE Plunkett', 'M Markande',
       'Mustafizur Rahman', 'Basil Thampi', 'BB Sran', 'AD Hales',
       'MK Lomror', 'Mohammed Siraj', 'DR Shorey', 'MM Ali', 'P Chopra',
       'IS Sodhi', 'Abhishek Sharma', 'JPR Scantlebury-Searles',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'KMA Paul',
       'N Pooran', 'P Ray Barman', 'S Lamichhane', 'SM Curran',
       'GC Viljoen', 'RD Chahar', 'M Prasidh Krishna', 'SD Lad',
       'R Parag', 'JL Denly', 'LS Livingstone', 'KK Ahmed', 'AJ Turner',
       'SE Rutherford', 'MJ Santner', 'P Simran Singh', 'JL Pattinson',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'CV Varun', 'KL Nagarkoti', 'I Udana', 'Ravi Bishnoi', 'AT Carey',
       'N Jagadeesan', 'A Nortje', 'Kartik Tyagi', 'SS Cottrell',
       'Arshdeep Singh', 'DR Sams'], dtype=object)

In [16]:
df1['player_dismissed']= df1['player_dismissed'].fillna('no_player_dismissed')

In [17]:
df1['player_dismissed']

0         no_player_dismissed
1         no_player_dismissed
2         no_player_dismissed
3         no_player_dismissed
4         no_player_dismissed
                 ...
193463    no_player_dismissed
193464    no_player_dismissed
193465    no_player_dismissed
193466    no_player_dismissed
193467    no_player_dismissed
Name: player_dismissed, Length: 193468, dtype: object

In [18]:
df1.isnull().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind           0
player_dismissed         0
fielder             186684
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [19]:
df1['fielder'].unique()

array([nan, 'P Kumar', 'CL White', 'JH Kallis', 'M Kartik', 'RT Ponting',
       'WP Saha', 'AB Agarkar,WP Saha', 'BB McCullum', 'IK Pathan',
       'KC Sangakkara', 'Joginder Sharma', 'P Amarnath', 'PA Patel',
       'M Manhas', 'B Geeves', 'V Kohli', 'Z Khan', 'MV Boucher',
       'AM Nayar', 'L Ronchi', 'RG Sharma', 'SB Styris', 'AB Dinda',
       'DJ Hussey', 'SC Ganguly', 'Mohammad Hafeez,WP Saha', 'LR Shukla',
       'Mohammad Hafeez', 'A Symonds', 'PP Chawla', 'Kamran Akmal',
       'RA Jadeja,Kamran Akmal', 'MK Tiwary,KD Karthik', 'GD McGrath',
       'G Gambhir', 'AC Gilchrist', 'S Dhawan', 'KD Karthik', 'DJ Bravo',
       'S Badrinath', 'Harbhajan Singh', 'JDP Oram', 'SK Raina',
       'RA Jadeja', 'D Kalyankrishna', 'VVS Laxman,RP Singh', 'SB Bangar',
       'D Salunkhe', 'DS Kulkarni', 'DJ Bravo,L Ronchi', 'A Nehra',
       'Harbhajan Singh,L Ronchi', 'B Lee', 'RR Sarwan',
       'AM Rahane (sub)', 'Yuvraj Singh', 'M Rawat,SR Watson', 'MM Patel',
       'GC Smith', 'M Rawat', 'Sohail Tanvir,M Rawat', 'A Kumble',
       'MS Dhoni,Joginder Sharma', 'I Sharma', 'M Muralitharan',
       'PP Ojha', 'VVS Laxman', 'V Sehwag,R Bhatia',
       'DPMD Jayawardene,KC Sangakkara', 'W Jaffer,MV Boucher',
       'MS Dhoni', 'MEK Hussey', 'R Vinay Kumar (sub)', 'R Dravid',
       'SK Raina,MS Dhoni', 'Joginder Sharma,JDP Oram,MS Dhoni',
       'RV Uthappa', 'AM Rahane,ST Jayasuriya', 'PR Shah',
       'ST Jayasuriya', 'V Sehwag', 'LRPL Taylor', 'VY Mahesh', 'K Goel',
       'S Sreesanth', 'Yuvraj Singh,KC Sangakkara', 'SE Marsh',
       'SK Trivedi', 'M Kaif', 'RA Jadeja,M Rawat', 'Umar Gul,WP Saha',
       'SR Watson', 'T Kohli (sub)', 'Shoaib Malik', 'PJ Sangwan',
       'SP Goswami', 'DW Steyn', 'B Akhil', 'LPC Silva', 'W Jaffer',
       'R Vinay Kumar', 'B Chipli (sub)', 'AS Yadav', 'DB Ravi Teja',
       'DB Das,DJ Hussey', 'BJ Hodge', 'JR Hopes', 'SM Pollock',
       'AB de Villiers', 'DJ Thornely', 'SS Tiwary', 'Sohail Tanvir',
       'SK Warne', 'M Ntini', 'U Kaul', 'DPMD Jayawardene', 'DT Patil',
       'RP Singh', 'Shahid Afridi', 'HH Gibbs', 'YV Takawale',
       'YK Pathan', 'SA Asnodkar', 'MK Tiwary', 'CK Kapugedera',
       'DW Steyn,MV Boucher', 'M Rawat,Sohail Tanvir',
       'YV Takawale,CRD Fernando', 'SR Tendulkar', 'CRD Fernando',
       'JA Morkel', 'SP Fleming', 'S Vidyut', 'Salman Butt', 'A Chopra',
       'Niraj Patel', 'V Sehwag,KD Karthik', 'PP Chawla,U Kaul',
       'T Taibu', 'TM Dilshan,AB de Villiers', 'MF Maharoof',
       'LR Shukla,WP Saha', 'RR Raje', 'Younis Khan',
       'YK Pathan,SR Watson', 'WA Mota', 'TM Dilshan',
       'AB de Villiers (sub)', 'Shoaib Malik (sub)',
       'RV Uthappa,SM Pollock', 'LA Pomersbach', 'RR Powar',
       'Misbah-ul-Haq', 'MS Gony', 'R Bhatia', 'B Chipli',
       'CL White,SP Goswami', 'MF Maharoof,Shoaib Malik (sub),KD Karthik',
       'V Sehwag,MF Maharoof', 'DR Smith', 'Yuvraj Singh,PP Chawla',
       'TM Srivastava', 'TM Srivastava,DPMD Jayawardene,U Kaul',
       'VRV Singh', 'R Dravid,SP Goswami', 'SD Chitnis',
       'MS Dhoni,PA Patel', 'A Mukund', 'S Badrinath,PA Patel',
       'Sohail Tanvir,Kamran Akmal', 'T Kohli', 'RA Jadeja (sub)',
       'SB Bangar,SB Styris', 'Pankaj Singh', 'MK Pandey',
       'RR Raje,ST Jayasuriya', 'L Balaji', 'MS Gony,PA Patel',
       'TM Dilshan,KD Karthik', 'YK Pathan,M Rawat', 'M Ntini,MS Gony',
       'ML Hayden', 'T Thushara', 'R Ashwin', 'V Kohli,RV Uthappa',
       'JD Ryder', 'KD Karthik,DL Vettori', 'DL Vettori', 'DP Nannes',
       'MC Henriques', 'LR Shukla,BB McCullum', 'Harmeet Singh',
       'R Bishnoi', 'A Flintoff', 'A Chopra,BB McCullum', 'Yashpal Singh',
       'CH Gayle', 'Y Venugopal Rao', 'AC Gilchrist,Harmeet Singh',
       'KP Pietersen', 'KV Sharma,RV Uthappa', 'DA Warner (sub)',
       'V Sehwag,DL Vettori', 'PJ Sangwan,DP Nannes', 'AS Raut',
       'Kamran Khan,M Rawat', 'Kamran Khan', 'RS Bopara',
       'R Vinay Kumar,RV Uthappa', 'DJ Bravo,Z Khan', 'A Mishra',
       'RA Jadeja,SA Asnodkar', 'Shoaib Ahmed', 'BAW Mendis', 'AN Ghosh',
       'JP Duminy', 'MN van Wyk', 'DL Vettori,KD Karthik',
       'AD Mascarenhas', 'JP Duminy,PR Shah', 'SL Malinga',
       'RE van der Merwe,MV Boucher', 'SM Katich',
       'HH Gibbs,Y Venugopal Rao', 'AB de Villiers,KD Karthik',
       'VS Malik', 'M Vijay', 'SB Jakati', 'SM Harwood', 'NV Ojha',
       'DJ Bravo,PR Shah', 'RJ Harris', 'V Kohli,MV Boucher', 'M Morkel',
       'LA Carseldine', 'DA Warner,KD Karthik', 'DA Warner',
       'HH Gibbs,AC Gilchrist', 'DB Ravi Teja,AC Gilchrist',
       'SM Katich,KC Sangakkara', 'SL Malinga,Harbhajan Singh',
       'TL Suman,AC Gilchrist', 'AC Gilchrist,Y Venugopal Rao',
       'AD Mathews', 'B Akhil,P Kumar', 'RE van der Merwe',
       'M Muralitharan,MS Dhoni', 'S Tyagi', 'SK Warne,MM Patel',
       'AM Rahane', 'Harbhajan Singh,ST Jayasuriya',
       'KC Sangakkara,WA Mota', 'S Sohal', 'ML Hayden,MS Dhoni',
       'TL Suman', 'AB Agarkar,BJ Hodge', 'Mashrafe Mortaza',
       'LR Shukla (sub)', 'KC Sangakkara,B Lee', 'AM Salvi', 'SS Shaikh',
       'J Botha,YK Pathan', 'RJ Quiney', 'Mohammad Ashraful',
       'TM Dilshan,PJ Sangwan', 'MV Boucher,P Kumar', 'Anirudh Singh',
       'P Dogra', 'R Sathish', 'DPMD Jayawardene,PP Chawla', 'MS Bisla',
       'EJG Morgan', 'FY Fazal (sub)', 'G Gambhir,A Mishra',
       'A Mishra,KD Karthik', 'Y Nagar (sub)', 'AT Rayudu', 'AP Tare',
       'R Dravid,MV Boucher', 'JM Kemp', 'Bipul Sharma', 'CA Pujara',
       'AC Voges', 'AS Raut (sub)', 'AD Mathews,M Kartik', 'KA Pollard',
       'WPUJC Vaas', 'RP Singh,AC Gilchrist', 'ML Hayden,JA Morkel',
       'GJ Bailey (sub)', 'J Theron', 'KP Appanna (sub)', 'SJ Srivastava',
       'AA Jhunjhunwala', 'SW Tait', 'PP Chawla,IK Pathan', 'MJ Lumb',
       'FY Fazal', 'AA Jhunjhunwala,SK Warne', 'A Mishra,DP Nannes',
       'UT Yadav,KD Karthik', 'MS Dhoni,T Thushara', 'SB Jakati,MS Dhoni',
       'AC Voges,NV Ojha', 'R McLaren', 'JP Duminy (sub)',
       'SL Malinga,AT Rayudu', 'SK Raina,SB Jakati', 'S Ladda,KD Karthik',
       'KAJ Roach', 'MK Pandey,RV Uthappa', 'S Narwal', 'S Anirudha',
       'DE Bollinger', 'KA Pollard,AT Rayudu', 'M Kaif (sub)',
       'KP Appanna', 'PD Collingwood', 'AA Bilakhia', 'AP Dole',
       'S Badrinath,MS Dhoni', 'AA Jhunjhunwala,FY Fazal,NV Ojha',
       'R Bhatia,DL Vettori', 'Iqbal Abdulla', 'RP Singh,Harmeet Singh',
       'B Sumanth', 'MD Mishra', 'AB Agarkar', 'RV Uthappa,JH Kallis',
       'RS Sodhi', 'J Theron,KC Sangakkara', 'K Goel,KC Sangakkara',
       'SS Tiwary,AT Rayudu', 'S Dhawan (sub)',
       'ST Jayasuriya,Harbhajan Singh', 'RG Sharma,AC Gilchrist',
       'DW Steyn,RV Uthappa', 'KA Pollard,C Madan', 'AG Murtaza',
       'JH Kallis,R Vinay Kumar', 'AC Voges,Kamran Khan', 'UT Yadav',
       'JD Unadkat,BB McCullum', 'JD Unadkat', 'MR Marsh,R Sharma',
       'AM Nayar,KA Pollard', 'M Vijay,MS Dhoni,JA Morkel',
       'R Ashwin,MS Dhoni', 'S Ladda', 'AG Paunikar', 'J Botha',
       'AL Menaria', 'R Sathish,DJ Jacobs', 'DJ Jacobs', 'JEC Franklin',
       'R Sharma', 'Yuvraj Singh,RV Uthappa', 'RN ten Doeschate',
       'IR Jaggi', 'PC Valthaty', 'S Randiv', 'S Randiv,S Anirudha',
       'WD Parnell,RV Uthappa', 'RV Uthappa,NL McCullum (sub)',
       'WD Parnell', 'RV Gomez,RA Jadeja', 'DT Christian',
       'AG Paunikar,FY Fazal (sub)', 'MA Agarwal', 'R Ninan',
       'Sunny Singh', 'AJ Finch', 'SB Wagh,RV Uthappa', 'SB Wagh',
       'Shakib Al Hasan,MS Bisla', 'NLTC Perera', 'AC Thomas',
       'KM Jadhav', 'PA Patel,RA Jadeja', 'DH Yagnik',
       'STR Binny,SR Watson', 'AB de Villiers,S Aravind', 'Y Nagar',
       'A Symonds,AN Ahmed', 'KA Pollard,DJ Jacobs', 'STR Binny',
       'J Botha,DH Yagnik', 'KM Jadhav,PA Patel', 'NL McCullum',
       'A Mukund (sub)', 'A Mithun,AB de Villiers',
       'PA Patel,NLTC Perera', 'RV Gomez', 'SP Goswami,B Lee',
       'L Balaji,B Lee', 'Y Nagar,NV Ojha', 'Shakib Al Hasan (sub)',
       'Harpreet Singh', 'J Syed Mohammad', 'RA Jadeja,PA Patel',
       'SP Goswami,Iqbal Abdulla', 'YK Pathan,SP Goswami',
       'EJG Morgan,SP Goswami', 'DH Yagnik,SK Trivedi',
       'F du Plessis (sub)', 'CL White,KC Sangakkara', 'AC Blizzard',
       'PA Patel,R Vinay Kumar', 'S Ladda,JH Kallis',
       'AB Agarkar,NV Ojha', 'A Mithun', 'AUK Pathan',
       'R Bhatia,MV Boucher', 'TL Suman,AT Rayudu',
       'KB Arun Karthik (sub)', 'M Kaif,AB de Villiers', 'B Kumar',
       'WP Saha,R Ashwin', 'CJ Ferguson', 'Mandeep Singh,AC Gilchrist',
       'AB de Villiers,KB Arun Karthik', 'KB Arun Karthik',
       'Y Nagar,IK Pathan', 'DJ Hussey,AC Gilchrist',
       'DT Christian,Anand Rajan', 'Mandeep Singh', 'OA Shah',
       'RA Jadeja,BJ Hodge', 'AA Chavan', 'Y Gnaneswara Rao',
       'DT Christian,PP Ojha', 'MS Dhoni,DE Bollinger', 'Anand Rajan',
       'KH Devdhar', 'AN Ahmed', 'S Aravind', 'RG Sharma,DS Kulkarni',
       'AN Ahmed,KD Karthik', 'Harbhajan Singh,KD Karthik',
       'AJ Finch,NV Ojha', 'KD Karthik,KA Pollard', 'A Singh',
       'KK Cooper', 'JP Faulkner', 'KK Cooper,SP Goswami',
       'DAJ Bracewell', 'DAJ Bracewell,GJ Maxwell', 'HV Patel',
       'HV Patel,AB de Villiers', 'DJ Harris', 'Iqbal Abdulla,R Bhatia',
       'SPD Smith,M Kartik', 'SPD Smith,RV Uthappa',
       'IK Pathan,DPMD Jayawardene', 'KP Pietersen,NV Ojha',
       'V Sehwag,NV Ojha', 'F du Plessis,R Ashwin', 'RE Levi',
       'RR Bhatkal', 'F du Plessis', 'TM Dilshan (sub)', 'SPD Smith',
       'P Awana', 'S Nadeem', 'RA Jadeja,R Ashwin',
       'DJ Bravo,KMDN Kulasekara', 'G Gambhir,R Bhatia', 'DB Das',
       'T Mishra', 'AB de Villiers,R Vinay Kumar', 'BB McCullum,MS Bisla',
       'KMDN Kulasekara', 'N Saini', 'AD Mathews,RV Uthappa',
       'SE Marsh,PP Chawla', 'DA Miller', 'DA Miller,N Saini',
       'JH Kallis,R Bhatia', 'LA Pomersbach (sub)',
       'LJ Wright,RV Uthappa', 'Azhar Mahmood', 'DJ Harris (sub)',
       'NLTC Perera (sub)', 'DPMD Jayawardene,NV Ojha', 'P Dogra (sub)',
       'GB Hogg', 'B Lee,BB McCullum', 'A Mishra,PA Patel',
       'KP Appanna,AB de Villiers', 'R Vinay Kumar,AB de Villiers',
       'DA Miller (sub)', 'RJ Peterson', 'RA Jadeja,MS Dhoni',
       'Gurkeerat Singh', 'WP Saha (sub)', 'V Kohli,J Syed Mohammad',
       'BB McCullum,SP Narine', 'MJ Clarke', 'A Ashish Reddy,J Theron',
       'KP Appanna,SS Tiwary', 'DR Smith,KD Karthik',
       'S Anirudha,MS Dhoni', 'BB McCullum,R Bhatia', 'VR Aaron',
       'P Negi', 'Harbhajan Singh,DR Smith', 'A Chandila', 'CA Lynn',
       'UBT Chand', 'PJ Sangwan (sub)', 'RA Jadeja,SB Jakati',
       'DA Warner,NV Ojha', 'DJ Bravo,R Ashwin', 'Shakib Al Hasan',
       'MS Bisla,SP Narine', 'SP Narine', 'MG Johnson',
       'JD Unadkat,KB Arun Karthik', 'MR Marsh', 'MN Samuels',
       'R Vinay Kumar,KB Arun Karthik', 'Ankit Sharma', 'A Ashish Reddy',
       'R Shukla', 'Mohammed Shami,MS Bisla', 'BMAJ Mendis', 'R Dhawan',
       'CH Morris', 'DT Christian (sub)', 'KL Rahul', 'PA Reddy',
       'GH Vihari', 'AT Rayudu,PP Ojha', 'SV Samson',
       'AC Gilchrist,P Kumar', 'IK Pathan,M Morkel', 'BB Samantray',
       'Q de Kock', 'R Dravid,DH Yagnik', 'MG Johnson,PP Ojha',
       'SK Raina,RA Jadeja', 'BMAJ Mendis,KM Jadhav',
       'PA Reddy,NLTC Perera', 'I Sharma,Q de Kock', 'DJ Bravo,MS Dhoni',
       'MM Sharma', 'SMSM Senanayake', 'R Rampaul', 'AD Russell',
       'M Vohra', 'S Kaul', 'BJ Rohrer', 'BB McCullum (sub)', 'DJG Sammy',
       'JH Kallis,MS Bisla', 'AB de Villiers,J Syed Mohammad',
       'DB Das,L Balaji', 'LJ Wright', 'JP Faulkner,SV Samson',
       'V Kohli,AB de Villiers', 'JA Morkel,R Ashwin', 'KV Sharma',
       'R Sathish,Gurkeerat Singh', 'M Muralitharan,KB Arun Karthik',
       'GH Vihari,DJG Sammy', 'P Suyal', 'UA Birla', 'Sachin Baby',
       'RG Sharma,KD Karthik', 'L Balaji,MS Bisla', 'JO Holder',
       'K Upadhyay', 'BJ Rohrer,KM Jadhav', 'R Sathish,Harmeet Singh',
       'I Sharma,DJG Sammy', 'NLTC Perera,PA Patel', 'MS Bisla,JH Kallis',
       'AG Murtaza,RV Uthappa', 'LJ Wright,RV Uthappa,AD Mathews',
       'SR Watson,JP Faulkner,DH Yagnik', 'GJ Maxwell',
       'STR Binny,Sachin Baby,KK Cooper', 'GJ Maxwell,KD Karthik',
       'NM Coulter-Nile', 'BB Samantray,PA Patel', 'EJG Morgan,MS Bisla',
       'AM Rahane,JP Faulkner', 'R Shukla (sub),DH Yagnik',
       'MM Sharma,CH Morris', 'AR Patel (sub)', 'CJ Anderson',
       'GJ Bailey', 'KW Richardson', 'YS Chahal', 'S Rana',
       'NJ Maddinson', 'WD Parnell (sub)', 'Mohammed Shami', 'AR Patel',
       'BW Hilfenhaus', 'MA Starc', 'CM Gautam', 'AM Rahane,SV Samson',
       'YV Takawale,PA Patel', 'TG Southee', 'S Nadeem,Mohammed Shami',
       'AV Wankhade (sub)', 'IC Pandey', 'MK Pandey,MS Bisla', 'SA Yadav',
       'SPD Smith,SV Samson', 'KK Nair', 'BR Dunk',
       'MS Dhoni,BW Hilfenhaus', 'MC Henriques (sub)',
       'SK Raina,RA Jadeja,MM Sharma', 'PA Patel,MA Starc', 'LMP Simmons',
       'P Kumar,CM Gautam', 'SA Yadav,RV Uthappa', 'RR Rossouw (sub)',
       'RG Sharma,CM Gautam', 'MS Dhoni,BB McCullum',
       'R Shukla,Q de Kock', 'Shivam Sharma', 'M Vohra,Sandeep Sharma',
       'BCJ Cutting', 'NV Ojha,DJG Sammy', 'K Santokie', 'BE Hendricks',
       'Parvez Rasool', 'Yuvraj Singh,PA Patel', 'Sandeep Sharma',
       'V Kohli,YV Takawale', 'SK Raina,P Negi', 'KD Karthik,KM Jadhav',
       'Karanveer Singh', 'RV Uthappa,R Vinay Kumar',
       'R Dhawan,GJ Bailey', 'KK Nair,SV Samson', 'PP Chawla,RV Uthappa',
       'BR Dunk (sub)', 'GJ Maxwell,WP Saha', 'SS Iyer',
       'MS Dhoni,A Nehra', 'TA Boult', 'M Morkel,Shakib Al Hasan',
       'KD Karthik,VR Aaron', 'J Suchith', 'KS Williamson', 'RG More',
       'PJ Cummins', 'Anureet Singh', 'RN ten Doeschate,RV Uthappa',
       'RG Sharma,KA Pollard', 'MS Bisla,AN Ahmed', 'Imran Tahir',
       'R Tewatia', 'RR Rossouw', 'DR Smith,MS Dhoni', 'J Yadav (sub)',
       'HV Patel,V Kohli', 'D Wiese', 'HH Pandya (sub)',
       'GH Vihari,NV Ojha', 'JP Duminy,KM Jadhav', 'DJ Hooda',
       'DJ Hooda,SV Samson', 'TG Southee,SV Samson',
       'KA Pollard,R Vinay Kumar', 'B Aparajith (sub)',
       'J Suchith,R Vinay Kumar', 'P Negi,MS Dhoni',
       'G Gambhir,RN ten Doeschate', 'Bipul Sharma,NV Ojha', 'HH Pandya',
       'J Yadav', 'V Kohli,KD Karthik', 'Shakib Al Hasan,Azhar Mahmood',
       'HH Pandya,KA Pollard', 'MJ McClenaghan,PA Patel',
       'UBT Chand (sub)', 'STR Binny,JP Faulkner', 'YS Chahal,KD Karthik',
       'SN Khan', 'AF Milne', 'GB Hogg,RV Uthappa', 'C Munro',
       'TG Southee,PA Patel', 'CR Brathwaite', 'Z Khan,KK Nair,Q de Kock',
       'Shakib Al Hasan,RV Uthappa', 'KD Karthik,DJ Bravo',
       'MC Henriques,NV Ojha', 'AD Russell,RV Uthappa',
       'Harbhajan Singh,PA Patel', 'KH Pandya',
       'P Negi,CH Morris,Q de Kock', 'SS Iyer,Q de Kock',
       'Mustafizur Rahman', 'NS Naik', 'DA Miller,NS Naik',
       'SS Tiwary,MS Dhoni', 'JC Buttler', 'PV Tambe', 'BB Sran',
       'KW Richardson,KL Rahul', 'GJ Maxwell,MP Stoinis',
       'JP Faulkner,KD Karthik', 'Ishan Kishan', 'KC Cariappa', 'RR Pant',
       'SW Billings,Q de Kock', 'GJ Maxwell,Sandeep Sharma',
       'R Sathish (sub)', 'WP Saha,Sandeep Sharma',
       'R Sathish (sub),RV Uthappa', 'AM Rahane,MS Dhoni', 'SW Billings',
       'V Shankar (sub)', 'SR Watson,STR Binny', 'Z Khan,Q de Kock',
       'DA Miller,WP Saha', 'BB Sran,Yuvraj Singh', 'DJ Hooda,NV Ojha',
       'AT Rayudu,JC Buttler', 'Harbhajan Singh,KH Pandya', 'JJ Bumrah',
       'SR Watson,Iqbal Abdulla', 'UT Khawaja', 'CJ Jordan',
       'SR Watson,Sachin Baby', 'ER Dwivedi', 'AS Rajpoot,RV Uthappa',
       'KK Nair,Q de Kock', 'DL Chahar', 'F Behardien',
       'Shakib Al Hasan,Kuldeep Yadav', 'YS Chahal,KL Rahul',
       'Sachin Baby,KL Rahul', 'Kuldeep Yadav', 'CJ Jordan (sub)',
       'MS Dhoni,AB Dinda', 'N Rana', 'MP Stoinis', 'BA Stokes',
       'B Stanlake', 'Rashid Khan', 'MJ McClenaghan', 'R Dhawan (sub)',
       'CR Woakes', 'RD Chahar', 'C de Grandhomme', 'JJ Roy',
       'V Kohli,KM Jadhav', 'RA Tripathi', 'C de Grandhomme,RV Uthappa',
       'P Negi,KM Jadhav', 'V Shankar (sub),Yuvraj Singh',
       'BB McCullum,KD Karthik', 'K Rabada', 'KK Nair,RR Pant',
       'Basil Thampi', 'TS Mills', 'S Badree', 'Washington Sundar',
       'JD Unadkat,BA Stokes', 'SN Thakur', 'SN Thakur,MS Dhoni',
       'SP Jackson,G Gambhir', 'MA Agarwal (sub)', 'LH Ferguson,MS Dhoni',
       'NM Coulter-Nile,RV Uthappa', 'TM Head', 'Ankit Soni',
       'Mohammed Siraj', 'SP Jackson', 'R Powell (sub)',
       'SPD Smith,DT Christian', 'CR Brathwaite (sub)', 'MJ Guptill',
       'DA Warner,B Kumar', 'V Shankar', 'AR Patel,WP Saha',
       'A Mishra,Mohammed Shami', 'J Suchith (sub)', 'SS Iyer,Z Khan',
       'Vishnu Vinod', 'AS Rajpoot', 'J Suchith (sub),PA Patel',
       'DT Christian,SN Thakur', 'MA Wood', 'E Lewis', 'AJ Tye',
       'RK Singh', 'B Laughlin', 'Shivam Mavi (sub)', 'K Gowtham',
       'Mujeeb Ur Rahman', 'DJM Short', 'AP Tare (sub)', 'Shivam Mavi',
       'MK Tiwary (sub)', 'TK Curran', 'H Klaasen', 'LE Plunkett',
       'Avesh Khan', 'DJ Hooda (sub)', 'PP Shaw', 'M Markande',
       'AD Hales', 'Shubman Gill', 'DJ Willey', 'RK Singh (sub)',
       'AD Nath', 'JPR Scantlebury-Searles', 'M Prasidh Krishna',
       'RD Chahar (sub)', 'Abhishek Sharma', 'MM Ali', 'R Tewatia (sub)',
       'JC Archer', 'DR Shorey (sub)', 'S Dube', 'Rasikh Salam',
       'KK Nair (sub)', 'SO Hetmyer', 'NA Saini', 'P Chopra (sub)',
       'M Ashwin', 'JM Bairstow', 'Mohammad Nabi', 'H Klaasen (sub)',
       'SM Curran', 'S Lamichhane', 'CA Ingram', 'S Midhun', 'S Gopal',
       'KMA Paul', 'Milind Kumar (sub)', 'N Pooran', 'SE Rutherford',
       'R Parag', 'MJ Santner', 'P Simran Singh', 'LS Livingstone',
       'MK Lomror', 'O Thomas', 'S Sandeep Warrier',
       'Anmolpreet Singh (sub)', 'JL Pattinson', 'D Padikkal', 'PK Garg',
       'TU Deshpande', 'KL Nagarkoti', 'KK Ahmed', 'YBK Jaiswal',
       'I Udana', 'JDS Neesham', 'CV Varun', 'RD Gaikwad', 'AT Carey',
       'A Nortje', 'Ravi Bishnoi', 'AS Roy (sub)', 'Abdul Samad',
       'Shahbaz Ahmed', 'CJ Green (sub)', 'PK Garg (sub)',
       'SP Goswami (sub)', 'T Natarajan', 'Arshdeep Singh',
       'Lalit Yadav (sub)', 'Kartik Tyagi', 'DR Sams', 'P Negi (sub)',
       'A Zampa', 'KMA Paul (sub)', 'P Dubey'], dtype=object)

In [20]:
df1['fielder']= df1['fielder'].fillna('no_fielder')

In [21]:
df1['fielder']

0         no_fielder
1         no_fielder
2         no_fielder
3         no_fielder
4         no_fielder
             ...
193463    no_fielder
193464    no_fielder
193465    no_fielder
193466    no_fielder
193467    no_fielder
Name: fielder, Length: 193468, dtype: object

In [22]:
df1.isnull().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind           0
player_dismissed         0
fielder                  0
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [23]:
df1['extras_type']= df1['extras_type'].fillna('no_extras_type')

In [24]:
df1['extras_type']

0         no_extras_type
1         no_extras_type
2         no_extras_type
3         no_extras_type
4         no_extras_type
               ...
193463    no_extras_type
193464    no_extras_type
193465             wides
193466    no_extras_type
193467    no_extras_type
Name: extras_type, Length: 193468, dtype: object

In [25]:
df1.isnull().sum()

id                    0
inning                0
over                  0
ball                  0
batsman               0
non_striker           0
bowler                0
batsman_runs          0
extra_runs            0
total_runs            0
non_boundary          0
is_wicket             0
dismissal_kind        0
player_dismissed      0
fielder               0
extras_type           0
batting_team          0
bowling_team        191
dtype: int64

In [26]:
df1["bowling_team"].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Chennai Super Kings', 'Kings XI Punjab', 'Delhi Daredevils',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', nan,
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [27]:
df1['bowling_team']= df1['bowling_team'].fillna('no_bowling_team')

In [28]:
df1['bowling_team']

0         Royal Challengers Bangalore
1         Royal Challengers Bangalore
2         Royal Challengers Bangalore
3         Royal Challengers Bangalore
4         Royal Challengers Bangalore
                     ...
193463                 Mumbai Indians
193464                 Mumbai Indians
193465                 Mumbai Indians
193466                 Mumbai Indians
193467                 Mumbai Indians
Name: bowling_team, Length: 193468, dtype: object

In [29]:
df1.isnull().sum()

id                  0
inning              0
over                0
ball                0
batsman             0
non_striker         0
bowler              0
batsman_runs        0
extra_runs          0
total_runs          0
non_boundary        0
is_wicket           0
dismissal_kind      0
player_dismissed    0
fielder             0
extras_type         0
batting_team        0
bowling_team        0
dtype: int64

In [30]:
df2.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [31]:
df3=df2[df2['city'].isnull()]

In [32]:
df3

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
399,729281,NaN,2014-04-17,YS Chahal,Sharjah Cricket Stadium,1,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN,Aleem Dar,S Ravi
402,729287,NaN,2014-04-19,PA Patel,Dubai International Cricket Stadium,1,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,Aleem Dar,AK Chaudhary
403,729289,NaN,2014-04-19,JP Duminy,Dubai International Cricket Stadium,1,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,N,NaN,Aleem Dar,VA Kulkarni
404,729291,NaN,2014-04-20,GJ Maxwell,Sharjah Cricket Stadium,1,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,NaN,BF Bowden,M Erasmus
406,729295,NaN,2014-04-22,GJ Maxwell,Sharjah Cricket Stadium,1,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,N,NaN,M Erasmus,S Ravi
407,729297,NaN,2014-04-23,RA Jadeja,Dubai International Cricket Stadium,1,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,N,NaN,HDPK Dharmasena,RK Illingworth
408,729299,NaN,2014-04-24,CA Lynn,Sharjah Cricket Stadium,1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,N,NaN,Aleem Dar,VA Kulkarni
409,729301,NaN,2014-04-25,AJ Finch,Dubai International Cricket Stadium,1,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,N,NaN,M Erasmus,S Ravi
410,729303,NaN,2014-04-25,MM Sharma,Dubai International Cricket Stadium,1,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,N,NaN,BF Bowden,M Erasmus
413,729309,NaN,2014-04-27,M Vijay,Sharjah Cricket Stadium,1,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,N,NaN,Aleem Dar,VA Kulkarni
414,729311,NaN,2014-04-27,DR Smith,Sharjah Cricket Stadium,1,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,N,NaN,AK Chaudhary,VA Kulkarni
415,729313,NaN,2014-04-28,Sandeep Sharma,Dubai International Cricket Stadium,1,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,N,NaN,BF Bowden,S Ravi
417,729317,NaN,2014-04-30,B Kumar,Dubai International Cricket Stadium,1,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,N,NaN,HDPK Dharmasena,M Erasmus

In [33]:
df2.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [34]:
df3['venue'].unique()

array(['Sharjah Cricket Stadium', 'Dubai International Cricket Stadium'],
      dtype=object)

In [35]:
df4= df3[df3['venue']== 'Sharjah Cricket Stadium']

In [36]:
df4

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
399,729281,NaN,2014-04-17,YS Chahal,Sharjah Cricket Stadium,1,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN,Aleem Dar,S Ravi
404,729291,NaN,2014-04-20,GJ Maxwell,Sharjah Cricket Stadium,1,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,NaN,BF Bowden,M Erasmus
406,729295,NaN,2014-04-22,GJ Maxwell,Sharjah Cricket Stadium,1,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,N,NaN,M Erasmus,S Ravi
408,729299,NaN,2014-04-24,CA Lynn,Sharjah Cricket Stadium,1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,N,NaN,Aleem Dar,VA Kulkarni
413,729309,NaN,2014-04-27,M Vijay,Sharjah Cricket Stadium,1,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,N,NaN,Aleem Dar,VA Kulkarni
414,729311,NaN,2014-04-27,DR Smith,Sharjah Cricket Stadium,1,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,N,NaN,AK Chaudhary,VA Kulkarni

In [37]:
df4['city']

399    NaN
404    NaN
406    NaN
408    NaN
413    NaN
414    NaN
Name: city, dtype: object

In [38]:
df2['venue']== 'Sharjah Cricket Stadium'

0      False
1      False
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: venue, Length: 816, dtype: bool

In [39]:
df5=df2[df2['venue']== 'Sharjah Cricket Stadium']

In [40]:
df5

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
399,729281,NaN,2014-04-17,YS Chahal,Sharjah Cricket Stadium,1,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN,Aleem Dar,S Ravi
404,729291,NaN,2014-04-20,GJ Maxwell,Sharjah Cricket Stadium,1,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,NaN,BF Bowden,M Erasmus
406,729295,NaN,2014-04-22,GJ Maxwell,Sharjah Cricket Stadium,1,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,N,NaN,M Erasmus,S Ravi
408,729299,NaN,2014-04-24,CA Lynn,Sharjah Cricket Stadium,1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,N,NaN,Aleem Dar,VA Kulkarni
413,729309,NaN,2014-04-27,M Vijay,Sharjah Cricket Stadium,1,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,N,NaN,Aleem Dar,VA Kulkarni
414,729311,NaN,2014-04-27,DR Smith,Sharjah Cricket Stadium,1,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,N,NaN,AK Chaudhary,VA Kulkarni
759,1216495,Sharjah,2020-11-03,S Nadeem,Sharjah Cricket Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,10.0,N,NaN,C Shamshuddin,RK Illingworth
760,1216496,Sharjah,2020-09-22,SV Samson,Sharjah Cricket Stadium,0,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,runs,16.0,N,NaN,C Shamshuddin,VA Kulkarni
764,1216500,Sharjah,2020-10-09,R Ashwin,Sharjah Cricket Stadium,0,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,Delhi Capitals,runs,46.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
766,1216502,Sharjah,2020-10-31,Sandeep Sharma,Sharjah Cricket Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,5.0,N,NaN,KN Ananthapadmanabhan,K Srinivasan
773,1216509,Sharjah,2020-10-17,S Dhawan,Sharjah Cricket Stadium,0,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,bat,Delhi Capitals,wickets,5.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
779,1216515,Sharjah,2020-10-03,SS Iyer,Sharjah Cricket Stadium,0,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Capitals,runs,18.0,N,NaN,VA Kulkarni,RK Illingworth
784,1216520,Sharjah,2020-10-26,CH Gayle,Sharjah Cricket Stadium,0,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,8.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
785,1216521,Sharjah,2020-10-23,TA Boult,Sharjah Cricket Stadium,0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,10.0,N,NaN,C Shamshuddin,VA Kulkarni
791,1216527,Sharjah,2020-09-27,SV Samson,Sharjah Cricket Stadium,0,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,N,NaN,RK Illingworth,K Srinivasan
795,1216531,Sharjah,2020-10-15,KL Rahul,Sharjah Cricket Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,8.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
802,1216538,Sharjah,2020-10-04,TA Boult,Sharjah Cricket Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,runs,34.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
804,1216540,Sharjah,2020-10-12,AB de Villiers,Sharjah Cricket Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,82.0,N,NaN,RK Illingworth,K Srinivasan

In [41]:
df5[['city','venue']]

        city                    venue
399      NaN  Sharjah Cricket Stadium
404      NaN  Sharjah Cricket Stadium
406      NaN  Sharjah Cricket Stadium
408      NaN  Sharjah Cricket Stadium
413      NaN  Sharjah Cricket Stadium
414      NaN  Sharjah Cricket Stadium
759  Sharjah  Sharjah Cricket Stadium
760  Sharjah  Sharjah Cricket Stadium
764  Sharjah  Sharjah Cricket Stadium
766  Sharjah  Sharjah Cricket Stadium
773  Sharjah  Sharjah Cricket Stadium
779  Sharjah  Sharjah Cricket Stadium
784  Sharjah  Sharjah Cricket Stadium
785  Sharjah  Sharjah Cricket Stadium
791  Sharjah  Sharjah Cricket Stadium
795  Sharjah  Sharjah Cricket Stadium
802  Sharjah  Sharjah Cricket Stadium
804  Sharjah  Sharjah Cricket Stadium

In [42]:
df6 = df2[df2['venue'] == 'Dubai International Cricket Stadium']

In [43]:
df6

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
402,729287,NaN,2014-04-19,PA Patel,Dubai International Cricket Stadium,1,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,Aleem Dar,AK Chaudhary
403,729289,NaN,2014-04-19,JP Duminy,Dubai International Cricket Stadium,1,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,N,NaN,Aleem Dar,VA Kulkarni
407,729297,NaN,2014-04-23,RA Jadeja,Dubai International Cricket Stadium,1,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,N,NaN,HDPK Dharmasena,RK Illingworth
409,729301,NaN,2014-04-25,AJ Finch,Dubai International Cricket Stadium,1,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,N,NaN,M Erasmus,S Ravi
410,729303,NaN,2014-04-25,MM Sharma,Dubai International Cricket Stadium,1,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,N,NaN,BF Bowden,M Erasmus
415,729313,NaN,2014-04-28,Sandeep Sharma,Dubai International Cricket Stadium,1,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,N,NaN,BF Bowden,S Ravi
417,729317,NaN,2014-04-30,B Kumar,Dubai International Cricket Stadium,1,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,N,NaN,HDPK Dharmasena,M Erasmus
757,1216493,Dubai,2020-09-20,MP Stoinis,Dubai International Cricket Stadium,0,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,Y,NaN,AK Chaudhary,Nitin Menon
762,1216498,Dubai,2020-10-24,CJ Jordan,Dubai International Cricket Stadium,0,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,12.0,N,NaN,AY Dandekar,PR Reiffel
768,1216504,Dubai,2020-09-30,Shivam Mavi,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,37.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
771,1216507,Dubai,2020-10-11,R Tewatia,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,5.0,N,NaN,YC Barde,PR Reiffel
774,1216510,Dubai,2020-09-24,KL Rahul,Dubai International Cricket Stadium,0,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kings XI Punjab,runs,97.0,N,NaN,AK Chaudhary,PR Reiffel
777,1216513,Dubai,2020-10-04,SR Watson,Dubai International Cricket Stadium,0,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,N,NaN,AY Dandekar,Nitin Menon
780,1216516,Dubai,2020-10-02,PK Garg,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,7.0,N,NaN,AK Chaudhary,PR Reiffel
781,1216517,Dubai,2020-10-18,KL Rahul,Dubai International Cricket Stadium,0,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
782,1216518,Dubai,2020-10-22,MK Pandey,Dubai International Cricket Stadium,0,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,N,NaN,Nitin Menon,PR Reiffel
783,1216519,Dubai,2020-10-05,AR Patel,Dubai International Cricket Stadium,0,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Capitals,runs,59.0,N,NaN,Nitin Menon,YC Barde
786,1216522,Dubai,2020-10-17,AB de Villiers,Dubai International Cricket Stadium,0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,N,NaN,AK Chaudhary,Nitin Menon
788,1216524,Dubai,2020-10-27,WP Saha,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,88.0,N,NaN,AK Chaudhary,Nitin Menon
789,1216525,Dubai,2020-10-10,V Kohli,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,N,NaN,AK Chaudhary,PR Reiffel
792,1216528,Dubai,2020-10-13,RA Jadeja,Dubai International Cricket Stadium,0,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,N,NaN,AK Chaudhary,PR Reiffel
794,1216530,Dubai,2020-11-01,PJ Cummins,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,60.0,N,NaN,Nitin Menon,PR Reiffel
798,1216534,Dubai,2020-09-21,YS Chahal,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,N,NaN,AY Dandekar,Nitin Menon
799,1216535,Dubai,2020-10-31,Ishan Kishan,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,YC Barde,PR Reiffel
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,C Shamshuddin,RK Illingworth
803,1216539,Dubai,2020-09-25,PP Shaw,Dubai International Cricket Stadium,0,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Delhi Capitals,runs,44.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
806,1216542,Dubai,2020-10-08,JM Bairstow,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,N,NaN,AK Chaudhary,Nitin Menon
807,1216543,Dubai,2020-10-14,A Nortje,Dubai International Cricket Stadium,0,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,N,NaN,AK Chaudhary,Nitin Menon
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN,C Shamshuddin,RK Illingworth
810,1216546,Dubai,2020-10-20,S Dhawan,Dubai International Cricket Stadium,0,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,Kings XI Punjab,wickets,5.0,N,NaN,C Shamshuddin,RK Illingworth
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [44]:
df6[['venue', 'city']]

                                   venue   city
402  Dubai International Cricket Stadium    NaN
403  Dubai International Cricket Stadium    NaN
407  Dubai International Cricket Stadium    NaN
409  Dubai International Cricket Stadium    NaN
410  Dubai International Cricket Stadium    NaN
415  Dubai International Cricket Stadium    NaN
417  Dubai International Cricket Stadium    NaN
757  Dubai International Cricket Stadium  Dubai
762  Dubai International Cricket Stadium  Dubai
768  Dubai International Cricket Stadium  Dubai
771  Dubai International Cricket Stadium  Dubai
774  Dubai International Cricket Stadium  Dubai
777  Dubai International Cricket Stadium  Dubai
780  Dubai International Cricket Stadium  Dubai
781  Dubai International Cricket Stadium  Dubai
782  Dubai International Cricket Stadium  Dubai
783  Dubai International Cricket Stadium  Dubai
786  Dubai International Cricket Stadium  Dubai
788  Dubai International Cricket Stadium  Dubai
789  Dubai International Cricket Stadium  Dubai
792  Dubai International Cricket Stadium  Dubai
794  Dubai International Cricket Stadium  Dubai
798  Dubai International Cricket Stadium  Dubai
799  Dubai International Cricket Stadium  Dubai
800  Dubai International Cricket Stadium  Dubai
803  Dubai International Cricket Stadium  Dubai
806  Dubai International Cricket Stadium  Dubai
807  Dubai International Cricket Stadium  Dubai
808  Dubai International Cricket Stadium  Dubai
810  Dubai International Cricket Stadium  Dubai
811  Dubai International Cricket Stadium  Dubai
812  Dubai International Cricket Stadium  Dubai
815  Dubai International Cricket Stadium  Dubai

In [45]:
np.where(df2['venue']== 'Sharjah Cricket Stadium', 'Sharjah', df2['city'])

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Hyderabad', 'Chandigarh', 'Bangalore',
       'Chennai', 'Mumbai', 'Chandigarh', 'Bangalore', 'Kolkata', 'Delhi',
       'Hyderabad', 'Jaipur', 'Chennai', 'Hyderabad', 'Chandigarh',
       'Mumbai', 'Jaipur', 'Bangalore', 'Chennai', 'Mumbai', 'Delhi',
       'Kolkata', 'Jaipur', 'Bangalore', 'Chennai', 'Hyderabad', 'Jaipur',
       'Chandigarh', 'Kolkata', 'Mumbai', 'Chandigarh', 'Delhi', 'Mumbai',
       'Delhi', 'Jaipur', 'Hyderabad', 'Kolkata', 'Bangalore', 'Kolkata',
       'Mumbai', 'Chennai', 'Chandigarh', 'Delhi', 'Chennai', 'Bangalore',
       'Kolkata', 'Jaipur', 'Hyderabad', 'Mumbai', 'Mumbai', 'Mumbai',
       'Cape Town', 'Cape Town', 'Cape Town', 'Cape Town',
       'Port Elizabeth', 'Durban', 'Cape Town', 'Durban', 'Cape Town',
       'Durban', 'Durban', 'Port Elizabeth', 'Cape Town', 'Durban',
       'Port Elizabeth', 'Centurion', 'Durban', 'Durban', 'Centurion',
       'Centurion', 'East London', 'Durban', 'Port Elizabeth',
       'Johannesburg', 'Port Elizabeth', 'Johannesburg', 'East London',
       'Durban', 'Durban', 'Centurion', 'Centurion', 'Centurion',
       'East London', 'Kimberley', 'Kimberley', 'Port Elizabeth',
       'Johannesburg', 'Kimberley', 'Centurion', 'Centurion', 'Durban',
       'Durban', 'Durban', 'Bloemfontein', 'Port Elizabeth',
       'Johannesburg', 'Johannesburg', 'Bloemfontein', 'Centurion',
       'Johannesburg', 'Durban', 'Durban', 'Centurion', 'Centurion',
       'Centurion', 'Johannesburg', 'Johannesburg', 'Mumbai', 'Mumbai',
       'Chandigarh', 'Kolkata', 'Chennai', 'Ahmedabad', 'Bangalore',
       'Kolkata', 'Delhi', 'Bangalore', 'Delhi', 'Cuttack', 'Ahmedabad',
       'Mumbai', 'Cuttack', 'Chennai', 'Mumbai', 'Bangalore',
       'Chandigarh', 'Mumbai', 'Ahmedabad', 'Chandigarh', 'Bangalore',
       'Ahmedabad', 'Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi',
       'Kolkata', 'Chandigarh', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi',
       'Nagpur', 'Chennai', 'Jaipur', 'Kolkata', 'Bangalore',
       'Chandigarh', 'Nagpur', 'Bangalore', 'Delhi', 'Jaipur', 'Nagpur',
       'Mumbai', 'Chennai', 'Jaipur', 'Chennai', 'Dharamsala',
       'Bangalore', 'Kolkata', 'Dharamsala', 'Delhi', 'Kolkata', 'Mumbai',
       'Mumbai', 'Mumbai', 'Mumbai', 'Chennai', 'Hyderabad', 'Kochi',
       'Delhi', 'Mumbai', 'Kolkata', 'Jaipur', 'Bangalore', 'Chandigarh',
       'Mumbai', 'Hyderabad', 'Jaipur', 'Mumbai', 'Chennai', 'Hyderabad',
       'Mumbai', 'Kolkata', 'Kochi', 'Delhi', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Mumbai', 'Kolkata', 'Delhi', 'Hyderabad', 'Jaipur',
       'Chennai', 'Delhi', 'Mumbai', 'Kochi', 'Delhi', 'Jaipur',
       'Bangalore', 'Kochi', 'Kolkata', 'Jaipur', 'Chennai', 'Mumbai',
       'Delhi', 'Hyderabad', 'Chennai', 'Mumbai', 'Kochi', 'Hyderabad',
       'Bangalore', 'Kolkata', 'Mumbai', 'Bangalore', 'Chandigarh',
       'Jaipur', 'Hyderabad', 'Chandigarh', 'Jaipur', 'Chennai', 'Indore',
       'Bangalore', 'Mumbai', 'Dharamsala', 'Indore', 'Mumbai',
       'Dharamsala', 'Chennai', 'Mumbai', 'Mumbai', 'Dharamsala', 'Delhi',
       'Bangalore', 'Kolkata', 'Mumbai', 'Mumbai', 'Chennai', 'Chennai',
       'Chennai', 'Kolkata', 'Mumbai', 'Jaipur', 'Bangalore',
       'Visakhapatnam', 'Jaipur', 'Pune', 'Visakhapatnam', 'Bangalore',
       'Delhi', 'Mumbai', 'Chennai', 'Chandigarh', 'Kolkata', 'Delhi',
       'Pune', 'Kolkata', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Chandigarh', 'Hyderabad', 'Chennai', 'Chandigarh', 'Chennai',
       'Delhi', 'Mumbai', 'Cuttack', 'Jaipur', 'Pune', 'Chandigarh',
       'Pune', 'Delhi', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Chennai', 'Cuttack', 'Jaipur', 'Bangalore', 'Pune', 'Chennai',
       'Kolkata', 'Chandigarh', 'Mumbai', 'Bangalore', 'Delhi', 'Pune',
       'Hyderabad', 'Mumbai', 'Jaipur', 'Pune', 'Kolkata', 'Chennai',
       'Jaipur', 'Chandigarh', 'Bangalore', 'Kolkata', 'Delhi', 'Mumbai',
       'Dharamsala', 'Delhi', 'Hyderabad', 'Dharamsala', 'Pune',
       'Hyderabad', 'Jaipur', 'Pune', 'Bangalore', 'Chennai', 'Chennai',
       'Kolkata', 'Bangalore', 'Hyderabad', 'Delhi', 'Chennai', 'Pune',
       'Hyderabad', 'Jaipur', 'Mumbai', 'Chandigarh', 'Bangalore', 'Pune',
       'Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Jaipur', 'Chennai',
       'Chandigarh', 'Bangalore', 'Pune', 'Jaipur', 'Delhi', 'Hyderabad',
       'Kolkata', 'Bangalore', 'Delhi', 'Chandigarh', 'Chennai',
       'Bangalore', 'Dharamsala', 'Kolkata', 'Chennai', 'Kolkata',
       'Jaipur', 'Mumbai', 'Chennai', 'Raipur', 'Jaipur', 'Mumbai',
       'Pune', 'Hyderabad', 'Raipur', 'Chennai', 'Pune', 'Kolkata',
       'Hyderabad', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Jaipur', 'Mumbai', 'Hyderabad', 'Chandigarh', 'Pune', 'Delhi',
       'Pune', 'Chandigarh', 'Ranchi', 'Jaipur', 'Delhi', 'Mumbai',
       'Ranchi', 'Chennai', 'Mumbai', 'Chandigarh', 'Hyderabad',
       'Dharamsala', 'Pune', 'Bangalore', 'Hyderabad', 'Delhi', 'Delhi',
       'Kolkata', 'Kolkata', 'Abu Dhabi', 'Sharjah', 'Abu Dhabi',
       'Abu Dhabi', nan, nan, 'Sharjah', 'Abu Dhabi', 'Sharjah', nan,
       'Sharjah', nan, nan, 'Abu Dhabi', 'Abu Dhabi', 'Sharjah',
       'Sharjah', nan, 'Abu Dhabi', nan, 'Ranchi', 'Mumbai', 'Delhi',
       'Bangalore', 'Ahmedabad', 'Delhi', 'Mumbai', 'Delhi', 'Cuttack',
       'Ahmedabad', 'Bangalore', 'Delhi', 'Mumbai', 'Cuttack',
       'Bangalore', 'Hyderabad', 'Ranchi', 'Bangalore', 'Hyderabad',
       'Cuttack', 'Ahmedabad', 'Ranchi', 'Hyderabad', 'Ahmedabad',
       'Delhi', 'Hyderabad', 'Kolkata', 'Chandigarh', 'Kolkata', 'Ranchi',
       'Mumbai', 'Chandigarh', 'Bangalore', 'Kolkata', 'Chandigarh',
       'Mumbai', 'Kolkata', 'Mumbai', 'Mumbai', 'Bangalore', 'Kolkata',
       'Chennai', 'Pune', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Bangalore', 'Ahmedabad', 'Kolkata', 'Pune', 'Visakhapatnam',
       'Mumbai', 'Visakhapatnam', 'Pune', 'Ahmedabad', 'Bangalore',
       'Delhi', 'Ahmedabad', 'Visakhapatnam', 'Bangalore', 'Delhi',
       'Ahmedabad', 'Mumbai', 'Chennai', 'Delhi', 'Chandigarh', 'Kolkata',
       'Bangalore', 'Chennai', 'Delhi', 'Mumbai', 'Bangalore',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Chennai', 'Kolkata',
       'Mumbai', 'Bangalore', 'Mumbai', 'Chennai', 'Kolkata', 'Raipur',
       'Mumbai', 'Chennai', 'Hyderabad', 'Raipur', 'Chandigarh', 'Mumbai',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Pune', 'Ranchi', 'Kolkata', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Bangalore', 'Kolkata', 'Rajkot', 'Delhi',
       'Hyderabad', 'Mumbai', 'Chandigarh', 'Bangalore', 'Hyderabad',
       'Chandigarh', 'Mumbai', 'Rajkot', 'Pune', 'Delhi', 'Hyderabad',
       'Rajkot', 'Pune', 'Chandigarh', 'Hyderabad', 'Delhi', 'Mumbai',
       'Pune', 'Delhi', 'Hyderabad', 'Rajkot', 'Pune', 'Bangalore',
       'Rajkot', 'Kolkata', 'Delhi', 'Hyderabad', 'Bangalore',
       'Chandigarh', 'Visakhapatnam', 'Kolkata', 'Chandigarh',
       'Visakhapatnam', 'Bangalore', 'Hyderabad', 'Visakhapatnam',
       'Bangalore', 'Kolkata', 'Chandigarh', 'Visakhapatnam', 'Kolkata',
       'Visakhapatnam', 'Bangalore', 'Kanpur', 'Raipur', 'Visakhapatnam',
       'Kanpur', 'Kolkata', 'Raipur', 'Bangalore', 'Delhi', 'Delhi',
       'Bangalore', 'Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bengaluru',
       'Hyderabad', 'Mumbai', 'Indore', 'Pune', 'Mumbai', 'Kolkata',
       'Bangalore', 'Rajkot', 'Kolkata', 'Delhi', 'Mumbai', 'Bangalore',
       'Delhi', 'Hyderabad', 'Rajkot', 'Hyderabad', 'Indore', 'Kolkata',
       'Mumbai', 'Pune', 'Rajkot', 'Kolkata', 'Mumbai', 'Pune',
       'Bangalore', 'Kolkata', 'Chandigarh', 'Pune', 'Rajkot',
       'Chandigarh', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Kolkata',
       'Delhi', 'Bangalore', 'Hyderabad', 'Delhi', 'Bangalore',
       'Chandigarh', 'Hyderabad', 'Chandigarh', 'Kanpur', 'Mumbai',
       'Delhi', 'Kanpur', 'Kolkata', 'Pune', 'Delhi', 'Mumbai',
       'Bangalore', 'Bangalore', 'Hyderabad', 'Mumbai', 'Chandigarh',
       'Kolkata', 'Hyderabad', 'Chennai', 'Jaipur', 'Hyderabad',
       'Bengaluru', 'Mumbai', 'Kolkata', 'Bengaluru', 'Chandigarh',
       'Kolkata', 'Mumbai', 'Jaipur', 'Chandigarh', 'Pune', 'Kolkata',
       'Bengaluru', 'Hyderabad', 'Jaipur', 'Delhi', 'Mumbai', 'Bengaluru',
       'Hyderabad', 'Delhi', 'Pune', 'Jaipur', 'Bengaluru', 'Pune',
       'Bengaluru', 'Delhi', 'Kolkata', 'Indore', 'Pune', 'Hyderabad',
       'Mumbai', 'Indore', 'Hyderabad', 'Jaipur', 'Kolkata', 'Delhi',
       'Jaipur', 'Indore', 'Delhi', 'Pune', 'Mumbai', 'Indore', 'Kolkata',
       'Mumbai', 'Bengaluru', 'Delhi', 'Jaipur', 'Hyderabad', 'Delhi',
       'Pune', 'Mumbai', 'Kolkata', 'Kolkata', 'Mumbai', 'Chennai',
       'Kolkata', 'Mumbai', 'Jaipur', 'Delhi', 'Kolkata', 'Bengaluru',
       'Hyderabad', 'Chandigarh', 'Delhi', 'Hyderabad', 'Chennai',
       'Chandigarh', 'Jaipur', 'Mumbai', 'Delhi', 'Bengaluru', 'Chennai',
       'Hyderabad', 'Bengaluru', 'Jaipur', 'Chandigarh', 'Chennai',
       'Mumbai', 'Jaipur', 'Kolkata', 'Mumbai', 'Chandigarh', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Chandigarh', 'Hyderabad', 'Delhi',
       'Kolkata', 'Jaipur', 'Delhi', 'Hyderabad', 'Bengaluru', 'Jaipur',
       'Chennai', 'Bengaluru', 'Kolkata', 'Chennai', 'Jaipur', 'Delhi',
       'Kolkata', 'Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai',
       'Chandigarh', 'Delhi', 'Bengaluru', 'Chandigarh', 'Mumbai',
       'Chennai', 'Visakhapatnam', 'Visakhapatnam', 'Hyderabad',
       'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Sharjah',
       'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Abu Dhabi',
       'Sharjah', 'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Abu Dhabi', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Abu Dhabi', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Dubai', 'Dubai', 'Dubai',
       'Sharjah', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Dubai', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Dubai', 'Sharjah',
       'Abu Dhabi', 'Abu Dhabi', 'Dubai', 'Dubai', 'Dubai', 'Abu Dhabi',
       'Sharjah', 'Dubai', 'Sharjah', 'Abu Dhabi', 'Dubai', 'Dubai',
       'Dubai', 'Abu Dhabi', 'Dubai', 'Dubai', 'Dubai', 'Abu Dhabi',
       'Abu Dhabi', 'Dubai'], dtype=object)

In [46]:
df2['city']= np.where(df2['venue']== 'Sharjah Cricket Stadium', 'Sharjah', df2['city'])

In [47]:
df2['city']

0       Bangalore
1      Chandigarh
2           Delhi
3          Mumbai
4         Kolkata
          ...
811         Dubai
812         Dubai
813     Abu Dhabi
814     Abu Dhabi
815         Dubai
Name: city, Length: 816, dtype: object

In [48]:
df2.isnull().sum()

id                   0
city                 7
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

Player of the Match

In [49]:
df2['player_of_match']

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [50]:
df2['player_of_match'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: player_of_match, Length: 816, dtype: bool

In [51]:
df2[df2['player_of_match'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
241,501265,Delhi,2011-05-21,NaN,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,NaN,NaN,NaN,NaN,SS Hazare,RJ Tucker
486,829763,Bangalore,2015-04-29,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN,JD Cloete,PG Pathak
511,829813,Bangalore,2015-05-17,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,NaN,NaN,NaN,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,Bengaluru,2019-04-30,NaN,M.Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN,UV Gandhe,NJ Llong

In [52]:
df2['player_of_match']=df2['player_of_match'].fillna('no_player_of_match')

In [53]:
df2['player_of_match']

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [54]:
df2['player_of_match'].isnull().sum()

np.int64(0)

In [55]:
df2.isnull().sum()

id                   0
city                 7
date                 0
player_of_match      0
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

Winner

In [56]:
df2['winner'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: winner, Length: 816, dtype: bool

In [57]:
df2[df2['winner'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
241,501265,Delhi,2011-05-21,no_player_of_match,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,NaN,NaN,NaN,NaN,SS Hazare,RJ Tucker
486,829763,Bangalore,2015-04-29,no_player_of_match,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN,JD Cloete,PG Pathak
511,829813,Bangalore,2015-05-17,no_player_of_match,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,NaN,NaN,NaN,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,Bengaluru,2019-04-30,no_player_of_match,M.Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN,UV Gandhe,NJ Llong

In [58]:
df2['winner']=df2['winner'].fillna('no_winner')

In [59]:
df2.isnull().sum()

id                   0
city                 7
date                 0
player_of_match      0
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               0
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [60]:
df2['result'].unique()

array(['runs', 'wickets', 'tie', nan], dtype=object)

In [61]:
df2['result'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: result, Length: 816, dtype: bool

In [62]:
df2[df2['result'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
241,501265,Delhi,2011-05-21,no_player_of_match,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no_winner,NaN,NaN,NaN,NaN,SS Hazare,RJ Tucker
486,829763,Bangalore,2015-04-29,no_player_of_match,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no_winner,NaN,NaN,NaN,NaN,JD Cloete,PG Pathak
511,829813,Bangalore,2015-05-17,no_player_of_match,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,no_winner,NaN,NaN,NaN,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,Bengaluru,2019-04-30,no_player_of_match,M.Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no_winner,NaN,NaN,NaN,NaN,UV Gandhe,NJ Llong

In [63]:
df2['result']= df2['result'].fillna('no_result')

In [64]:
df2.isnull().sum()

id                   0
city                 7
date                 0
player_of_match      0
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               0
result               0
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [65]:
df2['result_margin'] = df2['result_margin'].fillna('no_result_margin')
df2['method'] = df2['method'].fillna('no_result_method')
df2['city'] = df2['city'].fillna('no_city')
df2['eliminator'] = df2['eliminator'].fillna('no_eliminator')

In [66]:
df2.isnull().sum()

id                 0
city               0
date               0
player_of_match    0
venue              0
neutral_venue      0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
eliminator         0
method             0
umpire1            0
umpire2            0
dtype: int64

 Exploratory Data Analysis-EDA

Q1. What was the count of matches played in each season?

In [67]:
df1.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore

In [68]:
df2.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan

Q2.

In [69]:
year = []
for i in df2['date']:
  print(i.split('-')[0])
  year.append(i.split('-')[0])

2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2008
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2009
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2011
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2012
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2013
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2014
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2015
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2017
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2018
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2019
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020
2020

In [70]:
year

['2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020']

In [71]:
df2['year'] = year

In [72]:
df2.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri,2008
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar,2008
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper,2008
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008

In [73]:
df2['year'].value_counts()

year
2013    76
2012    74
2011    73
2014    60
2010    60
2020    60
2019    60
2016    60
2018    60
2015    59
2017    59
2008    58
2009    57
Name: count, dtype: int64

In [74]:
df2['year'] == 2008

0      False
1      False
2      False
3      False
4      False
       ...
811    False
812    False
813    False
814    False
815    False
Name: year, Length: 816, dtype: bool

In [75]:
df2[df2['year'] == '2008']

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri,2008
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar,2008
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper,2008
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008
5,335987,Jaipur,2008-04-21,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,N,no_result_method,Aleem Dar,RB Tiffin,2008
6,335988,Hyderabad,2008-04-22,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,IL Howell,AM Saheba,2008
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,no_result_method,DJ Harper,GA Pratapkumar,2008
8,335990,Hyderabad,2008-04-24,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,no_result_method,Asad Rauf,MR Benson,2008
9,335991,Chandigarh,2008-04-25,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,N,no_result_method,Aleem Dar,AM Saheba,2008
10,335992,Bangalore,2008-04-26,SR Watson,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,N,no_result_method,MR Benson,IL Howell,2008
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,no_result_method,BF Bowden,AV Jayaprakash,2008
12,335994,Mumbai,2008-04-27,AC Gilchrist,Dr DY Patil Sports Academy,0,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,N,no_result_method,Asad Rauf,SL Shastri,2008
13,335995,Chandigarh,2008-04-27,SM Katich,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,bat,Kings XI Punjab,wickets,4.0,N,no_result_method,RE Koertzen,I Shivram,2008
14,335996,Bangalore,2008-04-28,MS Dhoni,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,N,no_result_method,BR Doctrove,RB Tiffin,2008
15,335997,Kolkata,2008-04-29,ST Jayasuriya,Eden Gardens,0,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,Mumbai Indians,wickets,7.0,N,no_result_method,BF Bowden,AV Jayaprakash,2008
16,335998,Delhi,2008-04-30,GD McGrath,Feroz Shah Kotla,0,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Daredevils,runs,10.0,N,no_result_method,Aleem Dar,I Shivram,2008
17,335999,Hyderabad,2008-05-01,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,no_result_method,BR Doctrove,RB Tiffin,2008
18,336000,Jaipur,2008-05-01,SA Asnodkar,Sawai Mansingh Stadium,0,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,Rajasthan Royals,runs,45.0,N,no_result_method,RE Koertzen,GA Pratapkumar,2008
19,336001,Chennai,2008-05-02,V Sehwag,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,Delhi Daredevils,wickets,8.0,N,no_result_method,BF Bowden,K Hariharan,2008
20,336002,Hyderabad,2008-05-25,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
21,336003,Chandigarh,2008-05-03,IK Pathan,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Kolkata Knight Riders,Kings XI Punjab,bat,Kings XI Punjab,runs,9.0,N,no_result_method,DJ Harper,I Shivram,2008
22,336004,Mumbai,2008-05-04,SM Pollock,Dr DY Patil Sports Academy,0,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,runs,29.0,N,no_result_method,IL Howell,RE Koertzen,2008
23,336005,Jaipur,2008-05-04,Sohail Tanvir,Sawai Mansingh Stadium,0,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,bat,Rajasthan Royals,wickets,8.0,N,no_result_method,Asad Rauf,AV Jayaprakash,2008
24,336006,Bangalore,2008-05-05,S Sreesanth,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,N,no_result_method,SJ Davis,BR Doctrove,2008
25,336007,Chennai,2008-05-06,AC Gilchrist,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,7.0,N,no_result_method,MR Benson,RB Tiffin,2008
26,336008,Mumbai,2008-05-07,A Nehra,Dr DY Patil Sports Academy,0,Mumbai Indians,Rajasthan Royals,Mumbai Indians,field,Mumbai Indians,wickets,7.0,N,no_result_method,DJ Harper,RE Koertzen,2008
27,336009,Delhi,2008-05-08,MS Dhoni,Feroz Shah Kotla,0,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,N,no_result_method,Aleem Dar,RB Tiffin,2008
28,336010,Kolkata,2008-05-08,SC Ganguly,Eden Gardens,0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,5.0,N,no_result_method,Asad Rauf,IL Howell,2008
29,336011,Jaipur,2008-05-09,YK Pathan,Sawai Mansingh Stadium,0,Rajasthan Royals,Deccan Chargers,Rajasthan Royals,field,Rajasthan Royals,wickets,8.0,N,no_result_method,MR Benson,AM Saheba,2008
30,336012,Bangalore,2008-05-28,CRD Fernando,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,no_result_method,BF Bowden,AV Jayaprakash,2008
31,336013,Chennai,2008-05-10,L Balaji,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,Chennai Super Kings,runs,18.0,N,no_result_method,AV Jayaprakash,BG Jerling,2008
32,336014,Hyderabad,2008-05-11,SC Ganguly,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,23.0,N,no_result_method,IL Howell,AM Saheba,2008
33,336015,Jaipur,2008-05-11,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,no_result_method,SJ Davis,RE Koertzen,2008
34,336016,Chandigarh,2008-05-12,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,9.0,N,no_result_method,BR Doctrove,I Shivram,2008
35,336017,Kolkata,2008-05-13,Shoaib Akhtar,Eden Gardens,0,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,23.0,N,no_result_method,Asad Rauf,IL Howell,2008
36,336018,Mumbai,2008-05-14,ST Jayasuriya,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,no_result_method,BR Doctrove,AM Saheba,2008
37,336019,Chandigarh,2008-05-28,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Kings XI Punjab,runs,41.0,N,no_result_method,SJ Davis,K Hariharan,2008
38,336020,Delhi,2008-05-15,A Mishra,Feroz Shah Kotla,0,Delhi Daredevils,Deccan Chargers,Deccan Chargers,field,Delhi Daredevils,runs,12.0,N,no_result_method,BG Jerling,GA Pratapkumar,2008
39,336021,Mumbai,2008-05-16,SM Pollock,Wankhede Stadium,0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,Mumbai Indians,wickets,8.0,N,no_result_method,BR Doctrove,DJ Harper,2008
40,336022,Delhi,2008-05-17,DPMD Jayawardene,Feroz Shah Kotla,0,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Kings XI Punjab,runs,6.0,N,D/L,AV Jayaprakash,RE Koertzen,2008
41,336023,Jaipur,2008-05-17,GC Smith,Sawai Mansingh Stadium,0,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rajasthan Royals,runs,65.0,N,no_result_method,BF Bowden,SL Shastri,2008
42,336024,Hyderabad,2008-05-18,DJ Bravo,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Mumbai Indians,Deccan Chargers,field,Mumbai Indians,runs,25.0,N,no_result_method,BR Doctrove,DJ Harper,2008
43,336025,Kolkata,2008-05-18,M Ntini,Eden Gardens,0,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,runs,3.0,N,D/L,Asad Rauf,K Hariharan,2008
44,336026,Bangalore,2008-05-19,SP Goswami,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,wickets,5.0,N,no_result_method,SJ Davis,GA Pratapkumar,2008
45,336027,Kolkata,2008-05-20,YK Pathan,Eden Gardens,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,6.0,N,no_result_method,BG Jerling,RE Koertzen,2008
46,336028,Mumbai,2008-05-21,SE Marsh,Wankhede Stadium,0,Mumbai Indians,Kings XI Punjab,Mumbai Indians,field,Kings XI Punjab,runs,1.0,N,no_result_method,BF Bowden,GA Pratapkumar,2008
47,336029,Chennai,2008-05-21,A Kumble,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,14.0,N,no_result_method,DJ Harper,I Shivram,2008
48,336031,Chandigarh,2008-05-23,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Deccan Chargers,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,N,no_result_method,Asad Rauf,SJ Davis,2008
49,336032,Delhi,2008-05-24,KD Karthik,Feroz Shah Kotla,0,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,field,Delhi Daredevils,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008
50,336033,Chennai,2008-05-24,JA Morkel,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,10.0,N,no_result_method,DJ Harper,SL Shastri,2008
51,336034,Bangalore,2008-05-03,P Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,Royal Challengers Bangalore,runs,3.0,N,no_result_method,BR Doctrove,SL Shastri,2008
52,336035,Kolkata,2008-05-25,Umar Gul,Eden Gardens,0,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,bat,Kolkata Knight Riders,wickets,3.0,N,no_result_method,SJ Davis,I Shivram,2008
53,336036,Jaipur,2008-05-26,Sohail Tanvir,Sawai Mansingh Stadium,0,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,field,Rajasthan Royals,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008
54,336037,Hyderabad,2008-05-27,SK Raina,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Chennai Super Kings,Deccan Chargers,bat,Chennai Super Kings,wickets,7.0,N,no_result_method,BG Jerling,AM Saheba,2008
55,336038,Mumbai,2008-05-30,SR Watson,Wankhede Stadium,0,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,field,Rajasthan Royals,runs,105.0,N,no_result_method,BF Bowden,RE Koertzen,2008
56,336039,Mumbai,2008-05-31,M Ntini,Wankhede Stadium,0,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,bat,Chennai Super Kings,wickets,9.0,N,no_result_method,Asad Rauf,DJ Harper,2008
57,336040,Mumbai,2008-06-01,YK Pathan,Dr DY Patil Sports Academy,0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,no_result_method,BF Bowden,RE Koertzen,2008

In [76]:
len(df2[df2['year'] == '2008'])

58

In [77]:
for i in df2['year'].unique():
  print("year =", i,"/" ,"Number of Matches Played =", len(df2[df2['year'] == i]))

year = 2008 / Number of Matches Played = 58
year = 2009 / Number of Matches Played = 57
year = 2010 / Number of Matches Played = 60
year = 2011 / Number of Matches Played = 73
year = 2012 / Number of Matches Played = 74
year = 2013 / Number of Matches Played = 76
year = 2014 / Number of Matches Played = 60
year = 2015 / Number of Matches Played = 59
year = 2016 / Number of Matches Played = 60
year = 2017 / Number of Matches Played = 59
year = 2018 / Number of Matches Played = 60
year = 2019 / Number of Matches Played = 60
year = 2020 / Number of Matches Played = 60

Q.How many Runs Are Scored in Each Season?

In [78]:
df1.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore

In [79]:
df2.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri,2008
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar,2008
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper,2008
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008

In [80]:
df11 = pd.merge(df1,df2, on='id')

In [81]:
df11.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,...,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008

What were the Runs Scored per match in different season?

In [82]:
Total_Runs = df11.groupby(['year','id'])['total_runs'].sum()
print("Total run scored per season:\n",Total_Runs )

Total run scored per season:
 year  id
2008  335982     304
      335983     447
      335984     261
      335985     331
      335986     222
                ...
2020  1216547    402
      1237177    343
      1237178    263
      1237180    361
      1237181    313
Name: total_runs, Length: 816, dtype: int64

In [83]:
Number_of_matches = df2['year'].value_counts()
print(Number_of_matches)

year
2013    76
2012    74
2011    73
2014    60
2010    60
2020    60
2019    60
2016    60
2018    60
2015    59
2017    59
2008    58
2009    57
Name: count, dtype: int64

In [84]:
Avg_Runs_scored_per_match = Total_Runs / Number_of_matches
print("Avg_Runs Scored per match in each season:\n", Avg_Runs_scored_per_match)

Avg_Runs Scored per match in each season:
 year  id
2008  335982     5.241379
      335983     7.706897
      335984     4.500000
      335985     5.706897
      335986     3.827586
                   ...
2020  1216547    6.700000
      1237177    5.716667
      1237178    4.383333
      1237180    6.016667
      1237181    5.216667
Length: 816, dtype: float64

In [85]:
Runs_per_match_per_season = df11.groupby(['year', 'id'])['total_runs'].sum()
print("Total Runs Scored per Match in Each Season:\n", Runs_per_match_per_season)

Total Runs Scored per Match in Each Season:
 year  id
2008  335982     304
      335983     447
      335984     261
      335985     331
      335986     222
                ...
2020  1216547    402
      1237177    343
      1237178    263
      1237180    361
      1237181    313
Name: total_runs, Length: 816, dtype: int64

In [86]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print("Full Runs Scored per Match in Each Season:\n", Runs_per_match_per_season)
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

Full Runs Scored per Match in Each Season:
 year  id
2008  335982     304
      335983     447
      335984     261
      335985     331
      335986     222
      335987     334
      335988     285
      335989     410
      335990     431
      335991     298
      335992     273
      335993     299
      335994     309
      335995     320
      335996     343
      335997     275
      335998     372
      335999     331
      336000     347
      336001     341
      336002     336
      336003     347
      336004     295
      336005     219
      336006     253
      336007     292
      336008     207
      336009     375
      336010     253
      336011     281
      336012     248
      336013     344
      336014     385
      336015     315
      336016     287
      336017     243
      336018     314
      336019     401
      336020     376
      336021     135
      336022     212
      336023     329
      336024     331
      336025     204
      336026     312
      336027     297
      336028     377
      336029     238
      336031     353
      336032     355
      336033     412
      336034     309
      336035     349
      336036     291
      336037     295
      336038     279
      336039     228
      336040     327
2009  392181     311
      392182     191
      392183     162
      392184     205
      392185     266
      392186     237
      392188     344
      392189     369
      392190     300
      392191     341
      392192     324
      392194     299
      392195     251
      392196     334
      392197     282
      392198     290
      392199     282
      392200     235
      392201     298
      392202     290
      392203     287
      392204     282
      392205     283
      392206     308
      392207     307
      392208     299
      392209     278
      392210     344
      392211     311
      392212     271
      392213     212
      392214     359
      392215     234
      392216     337
      392217     281
      392218     298
      392219     248
      392220     279
      392221     349
      392222     241
      392223     334
      392224     261
      392225     288
      392226     243
      392227     298
      392228     326
      392229     267
      392230     286
      392231     377
      392232     269
      392233     203
      392234     208
      392235     331
      392236     328
      392237     307
      392238     295
      392239     280
2010  419106     311
      419107     420
      419108     288
      419109     271
      419110     349
      419111     283
      419112     407
      419113     273
      419114     338
      419115     185
      419116     375
      419117     334
      419118     302
      419119     306
      419120     332
      419121     272
      419122     311
      419123     306
      419124     335
      419125     361
      419126     299
      419127     327
      419128     349
      419129     337
      419130     303
      419131     314
      419132     327
      419133     323
      419134     309
      419135     338
      419136     365
      419137     469
      419138     293
      419139     404
      419140     331
      419141     316
      419142     306
      419143     310
      419144     348
      419145     370
      419146     312
      419147     277
      419148     322
      419149     223
      419150     311
      419151     289
      419152     327
      419153     282
      419154     262
      419155     225
      419156     352
      419157     325
      419158     265
      419159     387
      419160     279
      419161     268
      419162     333
      419163     246
      419164     168
      419165     314
2011  501198     304
      501199     278
      501200     323
      501201     194
      501202     225
      501203     317
      501204     303
      501205     283
      501206     381
      501207     299
      501208     317
      501209     319
      501210     366
      501211     345
      501212     331
      501213     377
      501214     166
      501215     266
      501216     320
      501218     242
      501219     258
      501220     342
      501221     320
      501222     346
      501223     433
      501224     307
      501225     220
      501226     259
      501227     321
      501228     286
      501229     203
      501230     279
      501231     189
      501232     336
      501233     276
      501234     239
      501235     287
      501236     311
      501237     295
      501238     281
      501239     318
      501240     296
      501241     299
      501242     295
      501243     354
      501244     325
      501245     175
      501246     324
      501247     253
      501248     239
      501249     329
      501250     273
      501251     250
      501252     297
      501253     334
      501254     359
      501255     194
      501256     260
      501257     311
      501258     195
      501259     274
      501260     353
      501261     293
      501262     237
      501263     267
      501264     314
      501265      56
      501266     257
      501267     353
      501268     352
      501269     295
      501270     327
      501271     352
2012  548306     227
      548307     197
      548308     230
      548309     351
      548310     294
      548311     312
      548312     306
      548313     310
      548314     280
      548315     288
      548316     221
      548317     367
      548318     413
      548319     231
      548320     268
      548321     319
      548322     311
      548323     266
      548324     331
      548325     185
      548326     393
      548327     368
      548328     251
      548329     380
      548330     315
      548331     329
      548332     293
      548333     364
      548334     327
      548335     253
      548336     332
      548337     294
      548339     339
      548341     336
      548342     377
      548343     305
      548344     333
      548345     303
      548346     201
      548347     279
      548348     359
      548349     285
      548350     321
      548351     239
      548352     310
      548353     293
      548354     311
      548355     347
      548356     366
      548357     307
      548358     251
      548359     315
      548360     283
      548361     253
      548362     311
      548363     337
      548364     229
      548365     295
      548366     384
      548367     344
      548368     318
      548369     276
      548370     248
      548371     243
      548372     409
      548373     254
      548374     286
      548375     238
      548376     255
      548377     325
      548378     306
      548379     336
      548380     358
      548381     382
2013  597998     257
      597999     310
      598000     230
      598001     325
      598002     287
      598003     199
      598004     260
      598005     269
      598006     374
      598007     277
      598008     312
      598009     293
      598010     229
      598011     325
      598012     331
      598013     312
      598014     250
      598015     294
      598016     310
      598017     304
      598018     227
      598019     271
      598020     252
      598021     250
      598022     243
      598023     240
      598024     326
      598025     371
      598026     371
      598027     396
      598028     335
      598029     321
      598030     319
      598031     299
      598032     290
      598033     330
      598034     386
      598035     313
      598036     344
      598037     344
      598038     291
      598039     259
      598040     273
      598041     357
      598042     357
      598043     265
      598044     161
      598045     350
      598046     218
      598047     360
      598048     323
      598049     309
      598050     275
      598051     369
      598052     292
      598053     258
      598054     362
      598055     228
      598056     270
      598057     231
      598058     285
      598059     241
      598060     362
      598061     333
      598062     303
      598063     318
      598064     384
      598065     249
      598066     316
      598067     306
      598068     188
      598069     262
      598070     336
      598071     267
      598072     334
      598073     273
2014  729279     285
      729281     291
      729283     411
      729285     268
      729287     231
      729289     333
      729291     384
      729293     261
      729295     314
      729297     273
      729299     298
      729301     364
      729303     283
      729305     141
      729307     241
      729309     251
      729311     291
      729313     251
      729315     304
      729317     329
      733971     262
      733973     338
      733975     308
      733977     313
      733979     330
      733981     359
      733983     355
      733985     321
      733987     418
      733989     236
      733991     364
      733993     187
      733995     317
      733997     299
      733999     381
      734001     317
      734003     297
      734005     356
      734007     416
      734009     283
      734011     340
      734013     280
      734015     288
      734017     331
      734019     329
      734021     321
      734023     310
      734025     315
      734027     360
      734029     374
      734031     331
      734033     342
      734035     314
      734037     321
      734039     234
      734041     384
      734043     298
      734045     349
      734047     428
      734049     399
2015  829705     338
      829707     299
      829709     298
      829711     373
      829713     356
      829715     370
      829717     336
      829719     338
      829721     329
      829723     334
      829725     334
      829727     258
      829729     372
      829731     330
      829733     314
      829735     313
      829737     400
      829739     293
      829741     382
      829743     277
      829745     335
      829747     343
      829749     264
      829751     294
      829753     287
      829757     194
      829759     280
      829761     329
      829763     200
      829765     266
      829767     237
      829769     366
      829771     226
      829773     362
      829775     321
      829777     364
      829779     272
      829781     299
      829783     305
      829785     314
      829787     395
      829789     317
      829791     367
      829793     320
      829795     431
      829797     302
      829799     365
      829801     239
      829803     190
      829805     337
      829807     218
      829809     264
      829811     389
      829813     189
      829815     227
      829817     349
      829819     289
      829821     279
      829823     363
2016  980901     247
      980903     197
      980905     323
      980907     409
      980909     375
      980911     327
      980913     224
      980915     288
      980917     290
      980919     305
      980921     383
      980923     287
      980925     279
      980927     341
      980929     272
      980931     357
      980933     318
      980935     289
      980937     362
      980939     322
      980941     353
      980943     212
      980945     343
      980947     352
      980949     391
      980951     345
      980953     373
      980955     285
      980957     320
      980959     374
      980961     299
      980963     321
      980965     328
      980967     255
      980969     386
      980971     353
      980973     269
      980975     322
      980977     349
      980979     270
      980981     304
      980983     296
      980985     251
      980987     352
      980989     169
      980991     359
      980993     332
      980995     369
      980997     197
      980999     331
      981001     249
      981003     319
      981005     345
      981007     345
      981009     320
      981011     277
      981013     317
      981015     302
      981017     325
      981019     408
2017  1082591    379
      1082592    371
      1082593    367
      1082594    327
      1082595    299
      1082596    275
      1082597    358
      1082598    298
      1082599    313
      1082600    317
      1082601    341
      1082602    287
      1082603    343
      1082604    327
      1082605    325
      1082606    353
      1082607    295
      1082608    337
      1082609    313
      1082610    405
      1082611    367
      1082612    397
      1082613    375
      1082614    270
      1082615    355
      1082616    350
      1082617    180
      1082618    317
      1082620    366
      1082621    269
      1082622    321
      1082623    388
      1082624    253
      1082625    306
      1082626    135
      1082627    370
      1082628    327
      1082629    328
      1082630    374
      1082631    313
      1082632    422
      1082633    257
      1082634    284
      1082635    278
      1082636    317
      1082637    381
      1082638    278
      1082639    320
      1082640    392
      1082641    453
      1082642    329
      1082643    312
      1082644    337
      1082645    151
      1082646    312
      1082647    304
      1082648    176
      1082649    218
      1082650    257
2018  1136561    334
      1136562    333
      1136563    353
      1136564    252
      1136565    407
      1136566    213
      1136567    298
      1136568    314
      1136569    389
      1136570    277
      1136571    415
      1136572    390
      1136573    329
      1136574    380
      1136575    323
      1136576    371
      1136577    344
      1136578    317
      1136579    350
      1136580    360
      1136581    335
      1136582    282
      1136583    205
      1136584    412
      1136585    251
      1136586    383
      1136587    339
      1136588    291
      1136589    351
      1136590    409
      1136591    320
      1136592    342
      1136593    357
      1136594    350
      1136595    255
      1136596    327
      1136597    349
      1136598    307
      1136599    287
      1136600    301
      1136601    318
      1136602    378
      1136603    353
      1136604    459
      1136605    368
      1136606    359
      1136607    339
      1136608    180
      1136609    287
      1136610    369
      1136611    422
      1136612    290
      1136613    298
      1136614    345
      1136615    337
      1136616    312
      1136617    279
      1136618    313
      1136619    334
      1136620    359
2019  1175356    141
      1175357    364
      1175358    389
      1175359    354
      1175360    297
      1175361    408
      1175362    368
      1175363    399
      1175364    353
      1175365    370
      1175366    344
      1175367    342
      1175368    318
      1175369    322
      1175370    303
      1175371    260
      1175372    411
      1178393    298
      1178394    232
      1178395    301
      1178396    279
      1178397    301
      1178398    219
      1178399    395
      1178400    306
      1178401    358
      1178402    375
      1178403    347
      1178404    323
      1178405    271
      1178406    343
      1178407    352
      1178408    269
      1178409    296
      1178410    416
      1178411    323
      1178412    329
      1178413    320
      1178414    321
      1178415    384
      1178416    351
      1178417    387
      1178418    352
      1178419    264
      1178420    321
      1178421    358
      1178422    430
      1178423    379
      1178424    103
      1178425    278
      1178426    324
      1178427    368
      1178428    236
      1178429    353
      1178430    343
      1178431    267
      1181764    263
      1181766    327
      1181767    298
      1181768    297
2020  1216492    328
      1216493    314
      1216494    169
      1216495    300
      1216496    416
      1216497    329
      1216498    240
      1216499    330
      1216500    322
      1216501    324
      1216502    241
      1216503    334
      1216504    311
      1216505    306
      1216506    307
      1216507    321
      1216508    341
      1216509    364
      1216510    315
      1216511    329
      1216512    326
      1216513    359
      1216514    312
      1216515    438
      1216516    321
      1216517    352
      1216518    310
      1216519    333
      1216520    299
      1216521    230
      1216522    356
      1216523    326
      1216524    350
      1216525    301
      1216526    297
      1216527    449
      1216528    314
      1216529    328
      1216530    322
      1216531    348
      1216532    309
      1216533    251
      1216534    316
      1216535    221
      1216536    350
      1216537    371
      1216538    382
      1216539    306
      1216540    306
      1216541    391
      1216542    333
      1216543    309
      1216544    295
      1216545    287
      1216546    331
      1216547    402
      1237177    343
      1237178    263
      1237180    361
      1237181    313
Name: total_runs, dtype: int64

Who umpired the most?

In [87]:
all_umpires = pd.concat([df2['umpire1'], df2['umpire2']])
Umpire_name_and_match_they_umpired = all_umpires.value_counts()
print(max(Umpire_name_and_match_they_umpired))

121

In [88]:
top_umpire = Umpire_name_and_match_they_umpired.index[0]
top_umpire_matches = Umpire_name_and_match_they_umpired.iloc[0]
print(f"{top_umpire} is an umpire who officiated {top_umpire_matches} matches.")

S Ravi is an umpire who officiated 121 matches.

Which Team Has Won Most tosses?

In [89]:
df1.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,no_dismissal,no_player_dismissed,no_fielder,no_extras_type,Kolkata Knight Riders,Royal Challengers Bangalore

In [90]:
df2.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri,2008
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar,2008
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper,2008
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008

In [91]:
Total_team = pd.concat([df2['team1'],df2['team2']])
Highest_toss_win = Total_team.value_counts()
print(max(Highest_toss_win))

203

In [92]:
Highest_toss_winner = Highest_toss_win.index[0]
Highest_toss_winner_matches = Highest_toss_win.iloc[0]
print(f"{Highest_toss_winner} won the highest toss, that is {Highest_toss_winner_matches} times.")

Mumbai Indians won the highest toss, that is 203 times.

What does team decide after winning the toss?

In [93]:
bat_or_bowled = df2['toss_decision'].value_counts()
print(bat_or_bowled)

toss_decision
field    496
bat      320
Name: count, dtype: int64

How Does Toss Decision Vary Across Season?

In [94]:
Toss_Decision_per_season = df2.groupby('year')['toss_decision'].value_counts().unstack(fill_value=0)
print("Toss Decisions per Season:\n", Toss_Decision_per_season)

Toss Decisions per Season:
 toss_decision  bat  field
year
2008            26     32
2009            35     22
2010            39     21
2011            25     48
2012            37     37
2013            45     31
2014            19     41
2015            25     34
2016            11     49
2017            11     48
2018            10     50
2019            10     50
2020            27     33

In [95]:
  Toss_Decision__per_season = df2.groupby('toss_decision')['year'].value_counts().unstack(fill_value=0)
  print(Toss_Decision__per_season)

year           2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  \
toss_decision
bat              26    35    39    25    37    45    19    25    11    11
field            32    22    21    48    37    31    41    34    49    48

year           2018  2019  2020
toss_decision
bat              10    10    27
field            50    50    33

In [96]:
df2['is_field_toss_decision'] = df2['toss_decision'] == 'field'
display(df2.head())

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,year,is_field_toss_decision
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,no_result_method,Asad Rauf,RE Koertzen,2008,True
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,no_result_method,MR Benson,SL Shastri,2008,False
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,no_result_method,Aleem Dar,GA Pratapkumar,2008,False
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,no_result_method,SJ Davis,DJ Harper,2008,False
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,no_result_method,BF Bowden,K Hariharan,2008,False

Does Winning the toss imply winning the game?

In [97]:
toss_winner_match_winner =  df2[df2['toss_winner']==df2['winner']]
Total_Number_of_toss_winner_match_winner = len(toss_winner_match_winner)
Total_number_of_matches = len(df2)
Percentage_of_toss_winner_match_winner = (Total_Number_of_toss_winner_match_winner/Total_number_of_matches)*100
print('Total number of toss winner who wons the match is',Total_Number_of_toss_winner_match_winner,',Total number of matches played is',Total_number_of_matches,'and the winning percentage is',Percentage_of_toss_winner_match_winner)

Total number of toss winner who wons the match is 418 ,Total number of matches played is 816 and the winning percentage is 51.225490196078425

How many times does the chassing team won the match?

In [98]:
chasing_team_wins = df2[(df2['toss_decision'] == 'field') & (df2['toss_winner'] == df2['winner']) | ((df2['toss_decision'] == 'bat') & (df2['toss_winner'] != df2['winner']))]
num_chasing_team_wins = len(chasing_team_wins)
print(f"The chasing team won the match {num_chasing_team_wins} times.")

The chasing team won the match 448 times.

Which all teams had won this tournament?

In [99]:
for i in df2['year'].unique():
    print(i, df2[df2['year']==i].tail(1)['winner'].values[0]  )

2008 Rajasthan Royals
2009 Deccan Chargers
2010 Chennai Super Kings
2011 Chennai Super Kings
2012 Kolkata Knight Riders
2013 Mumbai Indians
2014 Kolkata Knight Riders
2015 Mumbai Indians
2016 Sunrisers Hyderabad
2017 Mumbai Indians
2018 Chennai Super Kings
2019 Mumbai Indians
2020 Mumbai Indians

Which team has played the most number of matches?

In [100]:
all_teams_series = pd.concat([df2['team1'], df2['team2']])
team_counts = all_teams_series.value_counts()
Highest_match_playing_team_name = team_counts.idxmax()
Number_of_match_played = team_counts.max()
print('Highest match playing team is', Highest_match_playing_team_name , 'and number of matches they played is', Number_of_match_played )

Highest match playing team is Mumbai Indians and number of matches they played is 203

Which team has won the most number of times?

In [101]:
Highest_winnig_team = df2['winner'].value_counts().idxmax()
Number_of_match_played = df2['winner'].value_counts().max()
print( 'Highest winning team is ' , Highest_winnig_team , 'and number matches they have won are',Number_of_match_played )

Highest winning team is  Mumbai Indians and number matches they have won are 120

Which team has the highest winning percentage?

In [102]:
import pandas as pd

total_matches_played = pd.concat([df2['team1'], df2['team2']]).value_counts()
actual_winners = df2[df2['winner'] != 'no_winner']['winner']
matches_won = actual_winners.value_counts()
combined_stats = pd.DataFrame({'played': total_matches_played, 'won': matches_won}).fillna(0)
winning_percentage = (combined_stats['won'] / combined_stats['played'] * 100).fillna(0)
highest_winning_team = winning_percentage.idxmax()
highest_percentage = winning_percentage.max()

print(f"The team with the highest winning percentage is '{highest_winning_team}' with {highest_percentage:.2f}% wins.")

The team with the highest winning percentage is 'Rising Pune Supergiant' with 62.50% wins.

Is there any lucky venue for a particular team?

In [109]:
winner_venue = df2.groupby('venue')['winner'].value_counts()
Winner_name = winner_venue.idxmax(0)
winner_venue_name = winner_venue.max
print (Winner_name , winner_venue_name)

('Eden Gardens', 'Kolkata Knight Riders') <bound method Series.max of venue              winner
Barabati Stadium   Deccan Chargers            3
                   Kolkata Knight Riders      3
                   Kings XI Punjab            1
Brabourne Stadium  Mumbai Indians             6
                   Rajasthan Royals           2
                                             ..
Wankhede Stadium   Kochi Tuskers Kerala       1
                   Kolkata Knight Riders      1
                   Pune Warriors              1
                   Rising Pune Supergiants    1
                   Sunrisers Hyderabad        1
Name: count, Length: 252, dtype: int64>

In [104]:
winner_venue

venue              winner
Barabati Stadium   Deccan Chargers            3
                   Kolkata Knight Riders      3
                   Kings XI Punjab            1
Brabourne Stadium  Mumbai Indians             6
                   Rajasthan Royals           2
                                             ..
Wankhede Stadium   Kochi Tuskers Kerala       1
                   Kolkata Knight Riders      1
                   Pune Warriors              1
                   Rising Pune Supergiants    1
                   Sunrisers Hyderabad        1
Name: count, Length: 252, dtype: int64